In [90]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [91]:
df = pd.read_csv("car_data.csv")
print(df.head())

  Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol
1      sx4  2013           4.75           9.54       43000    Diesel
2     ciaz  2017           7.25           9.85        6900    Petrol
3  wagon r  2011           2.85           4.15        5200    Petrol
4    swift  2014           4.60           6.87       42450    Diesel

  Seller_Type Transmission  Owner
0      Dealer       Manual      0
1      Dealer       Manual      0
2      Dealer       Manual      0
3      Dealer       Manual      0
4      Dealer       Manual      0

In [92]:
df.drop(["Year" , "Owner" , "Present_Price"] , axis = 1 , inplace = True)
print(df.head())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type Transmission
0     ritz           3.35       27000    Petrol      Dealer       Manual
1      sx4           4.75       43000    Diesel      Dealer       Manual
2     ciaz           7.25        6900    Petrol      Dealer       Manual
3  wagon r           2.85        5200    Petrol      Dealer       Manual
4    swift           4.60       42450    Diesel      Dealer       Manual

In [93]:
pd.set_option('display.max_rows', None)
df['Car_Name'].value_counts()

Car_Name
city                         26
corolla altis                16
verna                        14
fortuner                     11
brio                         10
ciaz                          9
innova                        9
i20                           9
grand i10                     8
Royal Enfield Classic 350     7
amaze                         7
jazz                          7
sx4                           6
ertiga                        6
eon                           6
swift                         5
alto k10                      5
i10                           5
ritz                          4
wagon r                       4
dzire                         4
etios liva                    4
Royal Enfield Thunder 350     4
Bajaj Pulsar 150              4
etios cross                   3
etios g                       3
Royal Enfield Thunder 500     3
Bajaj Avenger 220             3
Honda CB Hornet 160R          3
Yamaha FZ S V 2.0             3
TVS Apache RTR 160            3
Bajaj Pulsar NS 200           3
xcent                         3
creta                         3
KTM RC200                     2
Royal Enfield Classic 500     2
Honda CBR 150                 2
Hero Extreme                  2
Bajaj Avenger 220 dtsi        2
Yamaha FZ  v 2.0              2
Bajaj Pulsar 220 F            2
TVS Apache RTR 180            2
Honda Activa 4G               2
Hero Splender iSmart          2
Activa 3g                     2
Hero Passion Pro              2
Honda Karizma                 2
Honda CB Shine                2
Honda CB twister              2
Bajaj Discover 125            2
elantra                       2
vitara brezza                 1
s cross                       1
alto 800                      1
ignis                         1
800                           1
baleno                        1
omni                          1
corolla                       1
etios gd                      1
camry                         1
land cruiser                  1
UM Renegade Mojave            1
Bajaj Dominar 400             1
KTM RC390                     1
Hyosung GT250R                1
KTM 390 Duke                  1
Mahindra Mojo XT300           1
Bajaj Pulsar RS200            1
Royal Enfield Bullet 350      1
Bajaj Avenger 150             1
Yamaha FZ 16                  1
Bajaj Avenger 150 street      1
Bajaj Pulsar  NS 200          1
Hero Passion X pro            1
Yamaha Fazer                  1
TVS Sport                     1
Honda Dream Yuga              1
Bajaj Avenger Street 220      1
Honda CB Trigger              1
Yamaha FZ S                   1
Bajaj Pulsar 135 LS           1
Activa 4g                     1
Honda CB Unicorn              1
Hero Honda CBZ extreme        1
Honda Activa 125              1
TVS Jupyter                   1
Hero Honda Passion Pro        1
Hero Splender Plus            1
Bajaj Discover 100            1
Suzuki Access 125             1
TVS Wego                      1
Hero Glamour                  1
Hero Super Splendor           1
Hero Hunk                     1
Hero  Ignitor Disc            1
Hero  CBZ Xtreme              1
Bajaj  ct 100                 1
Name: count, dtype: int64

In [94]:
pd.set_option('display.max_rows', None)
df['Seller_Type'].value_counts()

Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64

One hot encoding using pandas

In [95]:
pd.get_dummies(df,columns = ['Car_Name','Seller_Type'],dtype = int)

     Selling_Price  Kms_Driven Fuel_Type Transmission  Car_Name_800  \
0             3.35       27000    Petrol       Manual             0
1             4.75       43000    Diesel       Manual             0
2             7.25        6900    Petrol       Manual             0
3             2.85        5200    Petrol       Manual             0
4             4.60       42450    Diesel       Manual             0
5             9.25        2071    Diesel       Manual             0
6             6.75       18796    Petrol       Manual             0
7             6.50       33429    Diesel       Manual             0
8             8.75       20273    Diesel       Manual             0
9             7.45       42367    Diesel       Manual             0
10            2.85        2135    Petrol       Manual             0
11            6.85       51000    Diesel       Manual             0
12            7.50       15000    Petrol    Automatic             0
13            6.10       26000    Petrol       Manual             0
14            2.25       77427    Petrol       Manual             0
15            7.75       43000    Diesel       Manual             0
16            7.25       41678    Diesel       Manual             0
17            7.75       43000    Diesel       Manual             0
18            3.25       35500       CNG       Manual             0
19            2.65       41442    Petrol       Manual             0
20            2.85       25000    Petrol       Manual             0
21            4.90        2400    Petrol       Manual             0
22            4.40       50000    Petrol    Automatic             0
23            2.50       45280    Petrol       Manual             0
24            2.90       56879    Petrol       Manual             0
25            3.00       20000    Petrol       Manual             0
26            4.15       55138    Petrol       Manual             0
27            6.00       16200    Petrol       Manual             0
28            1.95       44542    Petrol       Manual             0
29            7.45       45000    Diesel       Manual             0
30            3.10       51439    Diesel       Manual             0
31            2.35       54200    Petrol       Manual             0
32            4.95       39000    Diesel       Manual             0
33            6.00       45000    Diesel       Manual             0
34            5.50       45000    Diesel       Manual             0
35            2.95       49998       CNG       Manual             0
36            4.65       48767    Petrol       Manual             0
37            0.35      127000    Petrol       Manual             1
38            3.00       10079    Petrol       Manual             0
39            2.25       62000    Petrol       Manual             0
40            5.85       24524    Petrol    Automatic             0
41            2.55       46706    Petrol       Manual             0
42            1.95       58000    Petrol       Manual             0
43            5.50       45780    Diesel       Manual             0
44            1.25       50000    Petrol       Manual             0
45            7.50       15000    Petrol    Automatic             0
46            2.65       64532    Petrol       Manual             0
47            1.05       65000    Petrol       Manual             0
48            5.80       25870    Petrol       Manual             0
49            7.75       37000    Petrol    Automatic             0
50           14.90      104707    Diesel    Automatic             0
51           23.00       40000    Diesel    Automatic             0
52           18.00       15000    Diesel    Automatic             0
53           16.00      135000    Diesel    Automatic             0
54            2.75       90000    Petrol       Manual             0
55            3.60       70000    Petrol    Automatic             0
56            4.50       40534    Petrol       Manual             0
57            4.75       50000    Petrol       Manual             0
58            4.10       39485    Petrol       Manual             0
59           19.99       41000    Diesel    Automatic             0
60            6.95       40001    Petrol       Manual             0
61            4.50       40588    Petrol       Manual             0
62           18.75       78000    Diesel    Automatic             0
63           23.50       47000    Diesel    Automatic             0
64           33.00        6000    Diesel    Automatic             0
65            4.75       45000    Diesel       Manual             0
66           19.75       11000    Petrol    Automatic             0
67            9.25       59000    Diesel       Manual             0
68            4.35       88000    Petrol       Manual             0
69           14.25       12000    Petrol       Manual             0
70            3.95       71000    Diesel       Manual             0
71            4.50       45000    Diesel       Manual             0
72            7.45       56001    Petrol       Manual             0
73            2.65       43000    Petrol       Manual             0
74            4.90       83000    Diesel       Manual             0
75            3.95       36000    Petrol       Manual             0
76            5.50       72000    Petrol       Manual             0
77            1.50      135154    Petrol    Automatic             0
78            5.25       80000    Petrol    Automatic             0
79           14.50       89000    Diesel    Automatic             0
80           14.73       23000    Diesel       Manual             0
81            4.75       40000    Diesel       Manual             0
82           23.00       15000    Diesel    Automatic             0
83           12.50       38000    Diesel       Manual             0
84            3.49      197176    Diesel       Manual             0
85            2.50      142000    Petrol    Automatic             0
86           35.00       78000    Diesel       Manual             0
87            5.90       56000    Petrol       Manual             0
88            3.45       47000    Petrol       Manual             0
89            4.75       40000    Petrol       Manual             0
90            3.80       62000    Petrol       Manual             0
91           11.25       58242    Diesel       Manual             0
92            3.51       75000    Petrol       Manual             0
93           23.00       40000    Diesel    Automatic             0
94            4.00       89000    Petrol    Automatic             0
95            5.85       72000    Petrol       Manual             0
96           20.75       29000    Diesel    Automatic             0
97           17.00        8700    Petrol       Manual             0
98            7.05       45000    Petrol       Manual             0
99            9.65       50024    Diesel       Manual             0
100           1.75        3000    Petrol       Manual             0
101           1.70        1400    Petrol       Manual             0
102           1.65        4000    Petrol       Manual             0
103           1.45        1200    Petrol       Manual             0
104           1.35        4100    Petrol       Manual             0
105           1.35       21700    Petrol       Manual             0
106           1.35       16500    Petrol       Manual             0
107           1.25       15000    Petrol       Manual             0
108           1.20       18000    Petrol       Manual             0
109           1.20       11000    Petrol       Manual             0
110           1.20        6000    Petrol       Manual             0
111           1.15        8700    Petrol       Manual             0
112           1.15        7000    Petrol       Manual             0
113           1.15       35000    Petrol       Manual             0
114           1.15       17000    Petrol       Manual             0
115           1.11       17500    Petrol       Manual             0
116           1.10       33000    Petrol       Manual             0
117           1.10       14000    Petrol       Manual             0
118           1.10       26000    Petrol       Manual             0
119           1.05        5400    Petrol       Manual             0
120           1.05        5700    Petrol       Manual             0
121           1.05        6900    Petrol       Manual             0
122           1.05        6000    Petrol       Manual             0
123           1.00       46500    Petrol       Manual             0
124           0.95       11500    Petrol       Manual             0
125           0.90       40000    Petrol       Manual             0
126           0.90        1300    Petrol       Manual             0
127           0.75        7000    Petrol       Manual             0
128           0.80        3000    Petrol       Manual             0
129           0.78        5000    Petrol       Manual             0
130           0.75       11000    Petrol       Manual             0
131           0.75       18000    Petrol       Manual             0
132           0.75        3500    Petrol       Manual             0
133           0.72         500    Petrol       Manual             0
134           0.65       11800    Petrol       Manual             0
135           0.65        5000    Petrol       Manual             0
136           0.65       23500    Petrol       Manual             0
137           0.65       16000    Petrol       Manual             0
138           0.60       15000    Petrol       Manual             0
139           0.60       16600    Petrol       Manual             0
140           0.60       32000    Petrol       Manual             0
141           0.60       20000    Petrol       Manual             0
142           0.60       29000    Petrol       Manual             0
143           0.60       25000    Petrol       Manual             0
144           0.60       25000    Petrol       Manual             0
145           0.60       19000    Petrol       Manual             0
146           0.55       15000    Petrol       Manual             0
147           0.55       58000    Petrol       Manual             0
148           0.52       45000    Petrol       Manual             0
149           0.51       24000    Petrol       Manual             0
150           0.50        6000    Petrol       Manual             0
151           0.50       31000    Petrol       Manual             0
152           0.50       13000    Petrol       Manual             0
153           0.50       45000    Petrol       Manual             0
154           0.50        8000    Petrol       Manual             0
155           0.48        4300    Petrol    Automatic             0
156           0.48       15000    Petrol       Manual             0
157           0.48       23000    Petrol       Manual             0
158           0.48        8600    Petrol       Manual             0
159           0.45        4000    Petrol    Automatic             0
160           0.45       24000    Petrol       Manual             0
161           0.45       23000    Petrol       Manual             0
162           0.45       14500    Petrol       Manual             0
163           0.45       27000    Petrol       Manual             0
164           0.45       14000    Petrol       Manual             0
165           0.45         500    Petrol    Automatic             0
166           0.45        1000    Petrol       Manual             0
167           0.42       42000    Petrol       Manual             0
168           0.42       12000    Petrol       Manual             0
169           0.40       14000    Petrol       Manual             0
170           0.40        5500    Petrol       Manual             0
171           0.40        6700    Petrol       Manual             0
172           0.40       13700    Petrol       Manual             0
173           0.40        1300    Petrol    Automatic             0
174           0.38       38600    Petrol       Manual             0
175           0.38       75000    Petrol       Manual             0
176           0.35       30000    Petrol       Manual             0
177           0.35       24000    Petrol    Automatic             0
178           0.35       19000    Petrol    Automatic             0
179           0.31      213000    Petrol       Manual             0
180           0.30       60000    Petrol       Manual             0
181           0.30       50000    Petrol       Manual             0
182           0.30       30000    Petrol       Manual             0
183           0.27       21000    Petrol       Manual             0
184           0.25       26000    Petrol       Manual             0
185           0.25        1900    Petrol    Automatic             0
186           0.25       22000    Petrol    Automatic             0
187           0.25       32000    Petrol       Manual             0
188           0.25       18000    Petrol       Manual             0
189           0.20       55000    Petrol       Manual             0
190           0.20       60000    Petrol       Manual             0
191           0.20       25000    Petrol       Manual             0
192           0.20       49000    Petrol       Manual             0
193           0.20       24000    Petrol       Manual             0
194           0.20       50000    Petrol       Manual             0
195           0.18       35000    Petrol       Manual             0
196           0.17      500000    Petrol    Automatic             0
197           0.16       33000    Petrol       Manual             0
198           0.15       35000    Petrol       Manual             0
199           0.12       53000    Petrol       Manual             0
200           0.10       92233    Petrol       Manual             0
201           3.25       58000    Diesel       Manual             0
202           4.40       28200    Petrol       Manual             0
203           2.95       53460    Petrol       Manual             0
204           2.75       28282    Petrol       Manual             0
205           5.25        3493    Petrol       Manual             0
206           5.75       12479    Petrol       Manual             0
207           5.15       34797    Petrol    Automatic             0
208           7.90        3435    Petrol       Manual             0
209           4.85       21125    Diesel       Manual             0
210           3.10       35775    Petrol       Manual             0
211          11.75       43535    Diesel       Manual             0
212          11.25       22671    Petrol       Manual             0
213           2.90       31604    Petrol       Manual             0
214           5.25       20114    Petrol       Manual             0
215           4.50       36100    Petrol       Manual             0
216           2.90       12500    Petrol       Manual             0
217           3.15       15000    Petrol       Manual             0
218           6.45       45078    Petrol       Manual             0
219           4.50       36000    Petrol       Manual             0
220           3.50       38488    Petrol       Manual             0
221           4.50       32000    Petrol    Automatic             0
222           6.00       77632    Diesel       Manual             0
223           8.25       61381    Diesel       Manual             0
224           5.11       36198    Petrol    Automatic             0
225           2.70       22517    Petrol       Manual             0
226           5.25       24678    Petrol       Manual             0
227           2.55       57000    Petrol       Manual             0
228           4.95       60000    Diesel       Manual             0
229           3.10       52132    Diesel       Manual             0
230           6.15       45000    Diesel       Manual             0
231           9.25       15001    Petrol       Manual             0
232          11.45       12900    Petrol    Automatic             0
233           3.90       53000    Diesel       Manual             0
234           5.50        4492    Petrol       Manual             0
235           9.10       15141    Petrol       Manual             0
236           3.10       11849    Petrol       Manual             0
237          11.25       68000    Diesel       Manual             0
238           4.80       60241    Petrol       Manual             0
239           2.00       23709    Petrol       Manual             0
240           5.35       32322    Diesel       Manual             0
241           4.75       35866    Petrol       Manual             0
242           4.40       34000    Petrol       Manual             0
243           6.25        7000    Petrol       Manual             0
244           5.95       49000    Diesel       Manual             0
245           5.20       71000    Diesel       Manual             0
246           3.75       35000    Petrol       Manual             0
247           5.95       36000    Petrol       Manual             0
248           4.00       30000    Petrol       Manual             0
249           5.25       17000    Petrol       Manual             0
250          12.90       35934    Diesel       Manual             0
251           5.00       56701    Petrol       Manual             0
252           5.40       31427    Petrol    Automatic             0
253           7.20       48000    Diesel       Manual             0
254           5.25       54242    Petrol       Manual             0
255           3.00       53675    Petrol       Manual             0
256          10.25       49562    Petrol       Manual             0
257           8.50       40324    Petrol       Manual             0
258           8.40       25000    Petrol       Manual             0
259           3.90       36054    Petrol       Manual             0
260           9.15       29223    Petrol       Manual             0
261           5.50        5600    Petrol       Manual             0
262           4.00       40023    Petrol       Manual             0
263           6.60       16002    Petrol       Manual             0
264           4.00       40026    Petrol       Manual             0
265           6.50       21200    Petrol       Manual             0
266           3.65       35000    Petrol       Manual             0
267           8.35       19434    Diesel       Manual             0
268           4.80       19000    Petrol       Manual             0
269           6.70       18828    Petrol       Manual             0
270           4.10       69341    Petrol       Manual             0
271           3.00       69562    Petrol       Manual             0
272           7.50       27600    Petrol       Manual             0
273           2.25       61203    Petrol       Manual             0
274           5.30       16500    Petrol       Manual             0
275          10.90       30753    Petrol    Automatic             0
276           8.65       24800    Petrol       Manual             0
277           9.70       21780    Petrol       Manual             0
278           6.00        4000    Petrol       Manual             0
279           6.25       40126    Petrol       Manual             0
280           5.25       14465    Petrol       Manual             0
281           2.10       50456    Petrol       Manual             0
282           8.25       63000    Diesel       Manual             0
283           8.99        9010    Petrol       Manual             0
284           3.50        9800    Petrol       Manual             0
285           7.40       15059    Petrol    Automatic             0
286           5.65       28569    Petrol       Manual             0
287           5.75       44000    Petrol    Automatic             0
288           8.40       34000    Petrol       Manual             0
289          10.11       10980    Petrol       Manual             0
290           4.50       19000    Petrol       Manual             0
291           5.40       31427    Petrol       Manual             0
292           6.40       12000    Petrol       Manual             0

optimizing one hot encoding doen by pamda by removing extra collumns

In [96]:
pd.get_dummies(df,columns = ['Car_Name','Seller_Type'],dtype = int,drop_first = True)

     Selling_Price  Kms_Driven Fuel_Type Transmission  Car_Name_Activa 3g  \
0             3.35       27000    Petrol       Manual                   0
1             4.75       43000    Diesel       Manual                   0
2             7.25        6900    Petrol       Manual                   0
3             2.85        5200    Petrol       Manual                   0
4             4.60       42450    Diesel       Manual                   0
5             9.25        2071    Diesel       Manual                   0
6             6.75       18796    Petrol       Manual                   0
7             6.50       33429    Diesel       Manual                   0
8             8.75       20273    Diesel       Manual                   0
9             7.45       42367    Diesel       Manual                   0
10            2.85        2135    Petrol       Manual                   0
11            6.85       51000    Diesel       Manual                   0
12            7.50       15000    Petrol    Automatic                   0
13            6.10       26000    Petrol       Manual                   0
14            2.25       77427    Petrol       Manual                   0
15            7.75       43000    Diesel       Manual                   0
16            7.25       41678    Diesel       Manual                   0
17            7.75       43000    Diesel       Manual                   0
18            3.25       35500       CNG       Manual                   0
19            2.65       41442    Petrol       Manual                   0
20            2.85       25000    Petrol       Manual                   0
21            4.90        2400    Petrol       Manual                   0
22            4.40       50000    Petrol    Automatic                   0
23            2.50       45280    Petrol       Manual                   0
24            2.90       56879    Petrol       Manual                   0
25            3.00       20000    Petrol       Manual                   0
26            4.15       55138    Petrol       Manual                   0
27            6.00       16200    Petrol       Manual                   0
28            1.95       44542    Petrol       Manual                   0
29            7.45       45000    Diesel       Manual                   0
30            3.10       51439    Diesel       Manual                   0
31            2.35       54200    Petrol       Manual                   0
32            4.95       39000    Diesel       Manual                   0
33            6.00       45000    Diesel       Manual                   0
34            5.50       45000    Diesel       Manual                   0
35            2.95       49998       CNG       Manual                   0
36            4.65       48767    Petrol       Manual                   0
37            0.35      127000    Petrol       Manual                   0
38            3.00       10079    Petrol       Manual                   0
39            2.25       62000    Petrol       Manual                   0
40            5.85       24524    Petrol    Automatic                   0
41            2.55       46706    Petrol       Manual                   0
42            1.95       58000    Petrol       Manual                   0
43            5.50       45780    Diesel       Manual                   0
44            1.25       50000    Petrol       Manual                   0
45            7.50       15000    Petrol    Automatic                   0
46            2.65       64532    Petrol       Manual                   0
47            1.05       65000    Petrol       Manual                   0
48            5.80       25870    Petrol       Manual                   0
49            7.75       37000    Petrol    Automatic                   0
50           14.90      104707    Diesel    Automatic                   0
51           23.00       40000    Diesel    Automatic                   0
52           18.00       15000    Diesel    Automatic                   0
53           16.00      135000    Diesel    Automatic                   0
54            2.75       90000    Petrol       Manual                   0
55            3.60       70000    Petrol    Automatic                   0
56            4.50       40534    Petrol       Manual                   0
57            4.75       50000    Petrol       Manual                   0
58            4.10       39485    Petrol       Manual                   0
59           19.99       41000    Diesel    Automatic                   0
60            6.95       40001    Petrol       Manual                   0
61            4.50       40588    Petrol       Manual                   0
62           18.75       78000    Diesel    Automatic                   0
63           23.50       47000    Diesel    Automatic                   0
64           33.00        6000    Diesel    Automatic                   0
65            4.75       45000    Diesel       Manual                   0
66           19.75       11000    Petrol    Automatic                   0
67            9.25       59000    Diesel       Manual                   0
68            4.35       88000    Petrol       Manual                   0
69           14.25       12000    Petrol       Manual                   0
70            3.95       71000    Diesel       Manual                   0
71            4.50       45000    Diesel       Manual                   0
72            7.45       56001    Petrol       Manual                   0
73            2.65       43000    Petrol       Manual                   0
74            4.90       83000    Diesel       Manual                   0
75            3.95       36000    Petrol       Manual                   0
76            5.50       72000    Petrol       Manual                   0
77            1.50      135154    Petrol    Automatic                   0
78            5.25       80000    Petrol    Automatic                   0
79           14.50       89000    Diesel    Automatic                   0
80           14.73       23000    Diesel       Manual                   0
81            4.75       40000    Diesel       Manual                   0
82           23.00       15000    Diesel    Automatic                   0
83           12.50       38000    Diesel       Manual                   0
84            3.49      197176    Diesel       Manual                   0
85            2.50      142000    Petrol    Automatic                   0
86           35.00       78000    Diesel       Manual                   0
87            5.90       56000    Petrol       Manual                   0
88            3.45       47000    Petrol       Manual                   0
89            4.75       40000    Petrol       Manual                   0
90            3.80       62000    Petrol       Manual                   0
91           11.25       58242    Diesel       Manual                   0
92            3.51       75000    Petrol       Manual                   0
93           23.00       40000    Diesel    Automatic                   0
94            4.00       89000    Petrol    Automatic                   0
95            5.85       72000    Petrol       Manual                   0
96           20.75       29000    Diesel    Automatic                   0
97           17.00        8700    Petrol       Manual                   0
98            7.05       45000    Petrol       Manual                   0
99            9.65       50024    Diesel       Manual                   0
100           1.75        3000    Petrol       Manual                   0
101           1.70        1400    Petrol       Manual                   0
102           1.65        4000    Petrol       Manual                   0
103           1.45        1200    Petrol       Manual                   0
104           1.35        4100    Petrol       Manual                   0
105           1.35       21700    Petrol       Manual                   0
106           1.35       16500    Petrol       Manual                   0
107           1.25       15000    Petrol       Manual                   0
108           1.20       18000    Petrol       Manual                   0
109           1.20       11000    Petrol       Manual                   0
110           1.20        6000    Petrol       Manual                   0
111           1.15        8700    Petrol       Manual                   0
112           1.15        7000    Petrol       Manual                   0
113           1.15       35000    Petrol       Manual                   0
114           1.15       17000    Petrol       Manual                   0
115           1.11       17500    Petrol       Manual                   0
116           1.10       33000    Petrol       Manual                   0
117           1.10       14000    Petrol       Manual                   0
118           1.10       26000    Petrol       Manual                   0
119           1.05        5400    Petrol       Manual                   0
120           1.05        5700    Petrol       Manual                   0
121           1.05        6900    Petrol       Manual                   0
122           1.05        6000    Petrol       Manual                   0
123           1.00       46500    Petrol       Manual                   0
124           0.95       11500    Petrol       Manual                   0
125           0.90       40000    Petrol       Manual                   0
126           0.90        1300    Petrol       Manual                   0
127           0.75        7000    Petrol       Manual                   0
128           0.80        3000    Petrol       Manual                   0
129           0.78        5000    Petrol       Manual                   0
130           0.75       11000    Petrol       Manual                   0
131           0.75       18000    Petrol       Manual                   0
132           0.75        3500    Petrol       Manual                   0
133           0.72         500    Petrol       Manual                   0
134           0.65       11800    Petrol       Manual                   0
135           0.65        5000    Petrol       Manual                   0
136           0.65       23500    Petrol       Manual                   0
137           0.65       16000    Petrol       Manual                   0
138           0.60       15000    Petrol       Manual                   0
139           0.60       16600    Petrol       Manual                   0
140           0.60       32000    Petrol       Manual                   0
141           0.60       20000    Petrol       Manual                   0
142           0.60       29000    Petrol       Manual                   0
143           0.60       25000    Petrol       Manual                   0
144           0.60       25000    Petrol       Manual                   0
145           0.60       19000    Petrol       Manual                   0
146           0.55       15000    Petrol       Manual                   0
147           0.55       58000    Petrol       Manual                   0
148           0.52       45000    Petrol       Manual                   0
149           0.51       24000    Petrol       Manual                   0
150           0.50        6000    Petrol       Manual                   0
151           0.50       31000    Petrol       Manual                   0
152           0.50       13000    Petrol       Manual                   0
153           0.50       45000    Petrol       Manual                   0
154           0.50        8000    Petrol       Manual                   0
155           0.48        4300    Petrol    Automatic                   0
156           0.48       15000    Petrol       Manual                   0
157           0.48       23000    Petrol       Manual                   0
158           0.48        8600    Petrol       Manual                   0
159           0.45        4000    Petrol    Automatic                   0
160           0.45       24000    Petrol       Manual                   0
161           0.45       23000    Petrol       Manual                   0
162           0.45       14500    Petrol       Manual                   0
163           0.45       27000    Petrol       Manual                   0
164           0.45       14000    Petrol       Manual                   0
165           0.45         500    Petrol    Automatic                   1
166           0.45        1000    Petrol       Manual                   0
167           0.42       42000    Petrol       Manual                   0
168           0.42       12000    Petrol       Manual                   0
169           0.40       14000    Petrol       Manual                   0
170           0.40        5500    Petrol       Manual                   0
171           0.40        6700    Petrol       Manual                   0
172           0.40       13700    Petrol       Manual                   0
173           0.40        1300    Petrol    Automatic                   0
174           0.38       38600    Petrol       Manual                   0
175           0.38       75000    Petrol       Manual                   0
176           0.35       30000    Petrol       Manual                   0
177           0.35       24000    Petrol    Automatic                   0
178           0.35       19000    Petrol    Automatic                   0
179           0.31      213000    Petrol       Manual                   0
180           0.30       60000    Petrol       Manual                   0
181           0.30       50000    Petrol       Manual                   0
182           0.30       30000    Petrol       Manual                   0
183           0.27       21000    Petrol       Manual                   0
184           0.25       26000    Petrol       Manual                   0
185           0.25        1900    Petrol    Automatic                   0
186           0.25       22000    Petrol    Automatic                   0
187           0.25       32000    Petrol       Manual                   0
188           0.25       18000    Petrol       Manual                   0
189           0.20       55000    Petrol       Manual                   0
190           0.20       60000    Petrol       Manual                   0
191           0.20       25000    Petrol       Manual                   0
192           0.20       49000    Petrol       Manual                   0
193           0.20       24000    Petrol       Manual                   0
194           0.20       50000    Petrol       Manual                   0
195           0.18       35000    Petrol       Manual                   0
196           0.17      500000    Petrol    Automatic                   1
197           0.16       33000    Petrol       Manual                   0
198           0.15       35000    Petrol       Manual                   0
199           0.12       53000    Petrol       Manual                   0
200           0.10       92233    Petrol       Manual                   0
201           3.25       58000    Diesel       Manual                   0
202           4.40       28200    Petrol       Manual                   0
203           2.95       53460    Petrol       Manual                   0
204           2.75       28282    Petrol       Manual                   0
205           5.25        3493    Petrol       Manual                   0
206           5.75       12479    Petrol       Manual                   0
207           5.15       34797    Petrol    Automatic                   0
208           7.90        3435    Petrol       Manual                   0
209           4.85       21125    Diesel       Manual                   0
210           3.10       35775    Petrol       Manual                   0
211          11.75       43535    Diesel       Manual                   0
212          11.25       22671    Petrol       Manual                   0
213           2.90       31604    Petrol       Manual                   0
214           5.25       20114    Petrol       Manual                   0
215           4.50       36100    Petrol       Manual                   0
216           2.90       12500    Petrol       Manual                   0
217           3.15       15000    Petrol       Manual                   0
218           6.45       45078    Petrol       Manual                   0
219           4.50       36000    Petrol       Manual                   0
220           3.50       38488    Petrol       Manual                   0
221           4.50       32000    Petrol    Automatic                   0
222           6.00       77632    Diesel       Manual                   0
223           8.25       61381    Diesel       Manual                   0
224           5.11       36198    Petrol    Automatic                   0
225           2.70       22517    Petrol       Manual                   0
226           5.25       24678    Petrol       Manual                   0
227           2.55       57000    Petrol       Manual                   0
228           4.95       60000    Diesel       Manual                   0
229           3.10       52132    Diesel       Manual                   0
230           6.15       45000    Diesel       Manual                   0
231           9.25       15001    Petrol       Manual                   0
232          11.45       12900    Petrol    Automatic                   0
233           3.90       53000    Diesel       Manual                   0
234           5.50        4492    Petrol       Manual                   0
235           9.10       15141    Petrol       Manual                   0
236           3.10       11849    Petrol       Manual                   0
237          11.25       68000    Diesel       Manual                   0
238           4.80       60241    Petrol       Manual                   0
239           2.00       23709    Petrol       Manual                   0
240           5.35       32322    Diesel       Manual                   0
241           4.75       35866    Petrol       Manual                   0
242           4.40       34000    Petrol       Manual                   0
243           6.25        7000    Petrol       Manual                   0
244           5.95       49000    Diesel       Manual                   0
245           5.20       71000    Diesel       Manual                   0
246           3.75       35000    Petrol       Manual                   0
247           5.95       36000    Petrol       Manual                   0
248           4.00       30000    Petrol       Manual                   0
249           5.25       17000    Petrol       Manual                   0
250          12.90       35934    Diesel       Manual                   0
251           5.00       56701    Petrol       Manual                   0
252           5.40       31427    Petrol    Automatic                   0
253           7.20       48000    Diesel       Manual                   0
254           5.25       54242    Petrol       Manual                   0
255           3.00       53675    Petrol       Manual                   0
256          10.25       49562    Petrol       Manual                   0
257           8.50       40324    Petrol       Manual                   0
258           8.40       25000    Petrol       Manual                   0
259           3.90       36054    Petrol       Manual                   0
260           9.15       29223    Petrol       Manual                   0
261           5.50        5600    Petrol       Manual                   0
262           4.00       40023    Petrol       Manual                   0
263           6.60       16002    Petrol       Manual                   0
264           4.00       40026    Petrol       Manual                   0
265           6.50       21200    Petrol       Manual                   0
266           3.65       35000    Petrol       Manual                   0
267           8.35       19434    Diesel       Manual                   0
268           4.80       19000    Petrol       Manual                   0

One hot encoding using One hot encoder of sklearn

In [97]:
print(df.head())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type Transmission
0     ritz           3.35       27000    Petrol      Dealer       Manual
1      sx4           4.75       43000    Diesel      Dealer       Manual
2     ciaz           7.25        6900    Petrol      Dealer       Manual
3  wagon r           2.85        5200    Petrol      Dealer       Manual
4    swift           4.60       42450    Diesel      Dealer       Manual

In [98]:
df['Transmission'] = df['Transmission'].map({
    'Manual' : 0 ,
    'Automatic' : 1
})
print(df.head())
print(df.tail())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type  Transmission
0     ritz           3.35       27000    Petrol      Dealer             0
1      sx4           4.75       43000    Diesel      Dealer             0
2     ciaz           7.25        6900    Petrol      Dealer             0
3  wagon r           2.85        5200    Petrol      Dealer             0
4    swift           4.60       42450    Diesel      Dealer             0
    Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type  Transmission
296     city           9.50       33988    Diesel      Dealer             0
297     brio           4.00       60000    Petrol      Dealer             0
298     city           3.35       87934    Petrol      Dealer             0
299     city          11.50        9000    Diesel      Dealer             0
300     brio           5.30        5464    Petrol      Dealer             0

In [99]:
pd.set_option('display.max_rows', None)
print(df['Transmission'])

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     1
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     1
41     0
42     0
43     0
44     0
45     1
46     0
47     0
48     0
49     1
50     1
51     1
52     1
53     1
54     0
55     1
56     0
57     0
58     0
59     1
60     0
61     0
62     1
63     1
64     1
65     0
66     1
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     1
78     1
79     1
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     1
94     1
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    1
156    0
157    0
158    0
159    1
160    0
161    0
162    0
163    0
164    0
165    1
166    0
167    0
168    0
169    0
170    0
171    0
172    0
173    1
174    0
175    0
176    0
177    1
178    1
179    0
180    0
181    0
182    0
183    0
184    0
185    1
186    1
187    0
188    0
189    0
190    0
191    0
192    0
193    0
194    0
195    0
196    1
197    0
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    1
208    0
209    0
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    0
218    0
219    0
220    0
221    1
222    0
223    0
224    1
225    0
226    0
227    0
228    0
229    0
230    0
231    0
232    1
233    0
234    0
235    0
236    0
237    0
238    0
239    0
240    0
241    0
242    0
243    0
244    0
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    1
253    0
254    0
255    0
256    0
257    0
258    0
259    0
260    0
261    0
262    0
263    0
264    0
265    0
266    0
267    0
268    0
269    0
270    0
271    0
272    0
273    0
274    0
275    1
276    0
277    0
278    0
279    0
280    0
281    0
282    0
283    0
284    0
285    1
286    0
287    1
288    0
289    0
290    0
291    0
292    0
293    0
294    0
295    0
296    0
297    0
298    0
299    0
300    0
Name: Transmission, dtype: int64

In [100]:
df['Transmission'].value_counts()

Transmission
0    261
1     40
Name: count, dtype: int64

In [101]:
print(df.head())

  Car_Name  Selling_Price  Kms_Driven Fuel_Type Seller_Type  Transmission
0     ritz           3.35       27000    Petrol      Dealer             0
1      sx4           4.75       43000    Diesel      Dealer             0
2     ciaz           7.25        6900    Petrol      Dealer             0
3  wagon r           2.85        5200    Petrol      Dealer             0
4    swift           4.60       42450    Diesel      Dealer             0

In [102]:
df['Fuel_Type'].value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [103]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
x = df.iloc[ : , 0 : 5]
y = df['Transmission']

In [104]:
x_train , x_test , y_train , y_test = train_test_split(x , y)

In [105]:
print(x)

                      Car_Name  Selling_Price  Kms_Driven Fuel_Type  \
0                         ritz           3.35       27000    Petrol
1                          sx4           4.75       43000    Diesel
2                         ciaz           7.25        6900    Petrol
3                      wagon r           2.85        5200    Petrol
4                        swift           4.60       42450    Diesel
5                vitara brezza           9.25        2071    Diesel
6                         ciaz           6.75       18796    Petrol
7                      s cross           6.50       33429    Diesel
8                         ciaz           8.75       20273    Diesel
9                         ciaz           7.45       42367    Diesel
10                    alto 800           2.85        2135    Petrol
11                        ciaz           6.85       51000    Diesel
12                        ciaz           7.50       15000    Petrol
13                      ertiga           6.10       26000    Petrol
14                       dzire           2.25       77427    Petrol
15                      ertiga           7.75       43000    Diesel
16                      ertiga           7.25       41678    Diesel
17                      ertiga           7.75       43000    Diesel
18                     wagon r           3.25       35500       CNG
19                         sx4           2.65       41442    Petrol
20                    alto k10           2.85       25000    Petrol
21                       ignis           4.90        2400    Petrol
22                         sx4           4.40       50000    Petrol
23                    alto k10           2.50       45280    Petrol
24                     wagon r           2.90       56879    Petrol
25                       swift           3.00       20000    Petrol
26                       swift           4.15       55138    Petrol
27                       swift           6.00       16200    Petrol
28                    alto k10           1.95       44542    Petrol
29                        ciaz           7.45       45000    Diesel
30                        ritz           3.10       51439    Diesel
31                        ritz           2.35       54200    Petrol
32                       swift           4.95       39000    Diesel
33                      ertiga           6.00       45000    Diesel
34                       dzire           5.50       45000    Diesel
35                         sx4           2.95       49998       CNG
36                       dzire           4.65       48767    Petrol
37                         800           0.35      127000    Petrol
38                    alto k10           3.00       10079    Petrol
39                         sx4           2.25       62000    Petrol
40                      baleno           5.85       24524    Petrol
41                    alto k10           2.55       46706    Petrol
42                         sx4           1.95       58000    Petrol
43                       dzire           5.50       45780    Diesel
44                        omni           1.25       50000    Petrol
45                        ciaz           7.50       15000    Petrol
46                        ritz           2.65       64532    Petrol
47                     wagon r           1.05       65000    Petrol
48                      ertiga           5.80       25870    Petrol
49                        ciaz           7.75       37000    Petrol
50                    fortuner          14.90      104707    Diesel
51                    fortuner          23.00       40000    Diesel
52                      innova          18.00       15000    Diesel
53                    fortuner          16.00      135000    Diesel
54                      innova           2.75       90000    Petrol
55               corolla altis           3.60       70000    Petrol
56                 etios cross           4.50       40534    Petrol
57               corolla altis           4.75       50000    Petrol
58                     etios g           4.10       39485    Petrol
59                    fortuner          19.99       41000    Diesel
60               corolla altis           6.95       40001    Petrol
61                 etios cross           4.50       40588    Petrol
62                    fortuner          18.75       78000    Diesel
63                    fortuner          23.50       47000    Diesel
64                    fortuner          33.00        6000    Diesel
65                  etios liva           4.75       45000    Diesel
66                      innova          19.75       11000    Petrol
67                    fortuner           9.25       59000    Diesel
68               corolla altis           4.35       88000    Petrol
69               corolla altis          14.25       12000    Petrol
70                  etios liva           3.95       71000    Diesel
71               corolla altis           4.50       45000    Diesel
72               corolla altis           7.45       56001    Petrol
73                  etios liva           2.65       43000    Petrol
74                 etios cross           4.90       83000    Diesel
75                     etios g           3.95       36000    Petrol
76               corolla altis           5.50       72000    Petrol
77                     corolla           1.50      135154    Petrol
78               corolla altis           5.25       80000    Petrol
79                    fortuner          14.50       89000    Diesel
80               corolla altis          14.73       23000    Diesel
81                    etios gd           4.75       40000    Diesel
82                      innova          23.00       15000    Diesel
83                      innova          12.50       38000    Diesel
84                      innova           3.49      197176    Diesel
85                       camry           2.50      142000    Petrol
86                land cruiser          35.00       78000    Diesel
87               corolla altis           5.90       56000    Petrol
88                  etios liva           3.45       47000    Petrol
89                     etios g           4.75       40000    Petrol
90               corolla altis           3.80       62000    Petrol
91                      innova          11.25       58242    Diesel
92                      innova           3.51       75000    Petrol
93                    fortuner          23.00       40000    Diesel
94               corolla altis           4.00       89000    Petrol
95               corolla altis           5.85       72000    Petrol
96                      innova          20.75       29000    Diesel
97               corolla altis          17.00        8700    Petrol
98               corolla altis           7.05       45000    Petrol
99                    fortuner           9.65       50024    Diesel
100  Royal Enfield Thunder 500           1.75        3000    Petrol
101         UM Renegade Mojave           1.70        1400    Petrol
102                  KTM RC200           1.65        4000    Petrol
103          Bajaj Dominar 400           1.45        1200    Petrol
104  Royal Enfield Classic 350           1.35        4100    Petrol
105                  KTM RC390           1.35       21700    Petrol
106             Hyosung GT250R           1.35       16500    Petrol
107  Royal Enfield Thunder 350           1.25       15000    Petrol
108  Royal Enfield Thunder 350           1.20       18000    Petrol
109  Royal Enfield Classic 350           1.20       11000    Petrol
110                  KTM RC200           1.20        6000    Petrol
111  Royal Enfield Thunder 350           1.15        8700    Petrol
112              KTM 390 Duke            1.15        7000    Petrol
113        Mahindra Mojo XT300           1.15       35000    Petrol
114  Royal Enfield Classic 350           1.15       17000    Petrol
115  Royal Enfield Classic 350           1.11       17500    Petrol
116  Royal Enfield Classic 350           1.10       33000    Petrol
117  Royal Enfield Thunder 500           1.10       14000    Petrol
118  Royal Enfield Classic 350           1.10       26000    Petrol
119  Royal Enfield Thunder 500           1.05        5400    Petrol
120         Bajaj Pulsar RS200           1.05        5700    Petrol
121  Royal Enfield Thunder 350           1.05        6900    Petrol
122   Royal Enfield Bullet 350           1.05        6000    Petrol
123  Royal Enfield Classic 350           1.00       46500    Petrol
124  Royal Enfield Classic 500           0.95       11500    Petrol
125  Royal Enfield Classic 500           0.90       40000    Petrol
126          Bajaj Avenger 220           0.90        1300    Petrol
127          Bajaj Avenger 150           0.75        7000    Petrol
128       Honda CB Hornet 160R           0.80        3000    Petrol
129          Yamaha FZ S V 2.0           0.78        5000    Petrol
130       Honda CB Hornet 160R           0.75       11000    Petrol
131               Yamaha FZ 16           0.75       18000    Petrol
132          Bajaj Avenger 220           0.75        3500    Petrol
133          Bajaj Avenger 220           0.72         500    Petrol
134         TVS Apache RTR 160           0.65       11800    Petrol
135           Bajaj Pulsar 150           0.65        5000    Petrol
136              Honda CBR 150           0.65       23500    Petrol
137               Hero Extreme           0.65       16000    Petrol
138       Honda CB Hornet 160R           0.60       15000    Petrol
139     Bajaj Avenger 220 dtsi           0.60       16600    Petrol
140              Honda CBR 150           0.60       32000    Petrol
141   Bajaj Avenger 150 street           0.60       20000    Petrol
142           Yamaha FZ  v 2.0           0.60       29000    Petrol
143           Yamaha FZ  v 2.0           0.60       25000    Petrol
144       Bajaj Pulsar  NS 200           0.60       25000    Petrol
145         TVS Apache RTR 160           0.60       19000    Petrol
146               Hero Extreme           0.55       15000    Petrol
147          Yamaha FZ S V 2.0           0.55       58000    Petrol
148         Bajaj Pulsar 220 F           0.52       45000    Petrol
149         Bajaj Pulsar 220 F           0.51       24000    Petrol
150         TVS Apache RTR 180           0.50        6000    Petrol
151         Hero Passion X pro           0.50       31000    Petrol
152        Bajaj Pulsar NS 200           0.50       13000    Petrol
153        Bajaj Pulsar NS 200           0.50       45000    Petrol
154              Yamaha Fazer            0.50        8000    Petrol
155            Honda Activa 4G           0.48        4300    Petrol
156                 TVS Sport            0.48       15000    Petrol
157          Yamaha FZ S V 2.0           0.48       23000    Petrol
158          Honda Dream Yuga            0.48        8600    Petrol
159            Honda Activa 4G           0.45        4000    Petrol
160   Bajaj Avenger Street 220           0.45       24000    Petrol
161         TVS Apache RTR 180           0.45       23000    Petrol
162        Bajaj Pulsar NS 200           0.45       14500    Petrol
163     Bajaj Avenger 220 dtsi           0.45       27000    Petrol
164       Hero Splender iSmart           0.45       14000    Petrol
165                  Activa 3g           0.45         500    Petrol
166           Hero Passion Pro           0.45        1000    Petrol
167         TVS Apache RTR 160           0.42       42000    Petrol
168           Honda CB Trigger           0.42       12000    Petrol
169       Hero Splender iSmart           0.40       14000    Petrol
170               Yamaha FZ S            0.40        5500    Petrol
171           Hero Passion Pro           0.40        6700    Petrol
172        Bajaj Pulsar 135 LS           0.40       13700    Petrol
173                  Activa 4g           0.40        1300    Petrol
174           Honda CB Unicorn           0.38       38600    Petrol
175     Hero Honda CBZ extreme           0.38       75000    Petrol
176              Honda Karizma           0.35       30000    Petrol
177           Honda Activa 125           0.35       24000    Petrol
178                TVS Jupyter           0.35       19000    Petrol
179              Honda Karizma           0.31      213000    Petrol
180     Hero Honda Passion Pro           0.30       60000    Petrol
181         Hero Splender Plus           0.30       50000    Petrol
182             Honda CB Shine           0.30       30000    Petrol
183         Bajaj Discover 100           0.27       21000    Petrol
184           Bajaj Pulsar 150           0.25       26000    Petrol
185          Suzuki Access 125           0.25        1900    Petrol
186                   TVS Wego           0.25       22000    Petrol
187           Honda CB twister           0.25       32000    Petrol
188               Hero Glamour           0.25       18000    Petrol
189        Hero Super Splendor           0.20       55000    Petrol
190           Bajaj Pulsar 150           0.20       60000    Petrol
191         Bajaj Discover 125           0.20       25000    Petrol
192                  Hero Hunk           0.20       49000    Petrol
193         Hero  Ignitor Disc           0.20       24000    Petrol
194           Hero  CBZ Xtreme           0.20       50000    Petrol
195              Bajaj  ct 100           0.18       35000    Petrol
196                  Activa 3g           0.17      500000    Petrol
197           Honda CB twister           0.16       33000    Petrol
198         Bajaj Discover 125           0.15       35000    Petrol
199             Honda CB Shine           0.12       53000    Petrol
200           Bajaj Pulsar 150           0.10       92233    Petrol
201                        i20           3.25       58000    Diesel
202                  grand i10           4.40       28200    Petrol
203                        i10           2.95       53460    Petrol
204                        eon           2.75       28282    Petrol
205                  grand i10           5.25        3493    Petrol
206                      xcent           5.75       12479    Petrol
207                  grand i10           5.15       34797    Petrol
208                        i20           7.90        3435    Petrol
209                  grand i10           4.85       21125    Diesel
210                        i10           3.10       35775    Petrol
211                    elantra          11.75       43535    Diesel
212                      creta          11.25       22671    Petrol
213                        i20           2.90       31604    Petrol
214                  grand i10           5.25       20114    Petrol
215                      verna           4.50       36100    Petrol
216                        eon           2.90       12500    Petrol
217                        eon           3.15       15000    Petrol
218                      verna           6.45       45078    Petrol
219                      verna           4.50       36000    Petrol
220                        eon           3.50       38488    Petrol
221                        i20           4.50       32000    Petrol
222                        i20           6.00       77632    Diesel
223                      verna           8.25       61381    Diesel
224                      verna           5.11       36198    Petrol
225                        i10           2.70       22517    Petrol
226                  grand i10           5.25       24678    Petrol
227                        i10           2.55       57000    Petrol
228                      verna           4.95       60000    Diesel
229                        i20           3.10       52132    Diesel
230                      verna           6.15       45000    Diesel
231                      verna           9.25       15001    Petrol
232                    elantra          11.45       12900    Petrol
233                  grand i10           3.90       53000    Diesel
234                  grand i10           5.50        4492    Petrol
235                      verna           9.10       15141    Petrol
236                        eon           3.10       11849    Petrol
237                      creta          11.25       68000    Diesel
238                      verna           4.80       60241    Petrol
239                        eon           2.00       23709    Petrol
240                      verna           5.35       32322    Diesel
241                      xcent           4.75       35866    Petrol
242                      xcent           4.40       34000    Petrol
243                        i20           6.25        7000    Petrol
244                      verna           5.95       49000    Diesel
245                      verna           5.20       71000    Diesel
246                        i20           3.75       35000    Petrol
247                      verna           5.95       36000    Petrol
248                        i10           4.00       30000    Petrol
249                        i20           5.25       17000    Petrol
250                      creta          12.90       35934    Diesel
251                       city           5.00       56701    Petrol
252                       brio           5.40       31427    Petrol
253                       city           7.20       48000    Diesel
254                       city           5.25       54242    Petrol
255                       brio           3.00       53675    Petrol
256                       city          10.25       49562    Petrol
257                       city           8.50       40324    Petrol
258                       city           8.40       25000    Petrol
259                      amaze           3.90       36054    Petrol
260                       city           9.15       29223    Petrol
261                       brio           5.50        5600    Petrol
262                      amaze           4.00       40023    Petrol
263                       jazz           6.60       16002    Petrol
264                      amaze           4.00       40026    Petrol
265                       jazz           6.50       21200    Petrol
266                      amaze           3.65       35000    Petrol
267                       city           8.35       19434    Diesel
268                       brio           4.80       19000    Petrol
269                       city           6.70       18828    Petrol
270                       city           4.10       69341    Petrol
271                       city           3.00       69562    Petrol
272                       city           7.50       27600    Petrol
273                       jazz           2.25       61203    Petrol
274                       brio           5.30       16500    Petrol
275                       city          10.90       30753    Petrol
276                       city           8.65       24800    Petrol
277                       city           9.70       21780    Petrol
278                       jazz           6.00        4000    Petrol
279                       city           6.25       40126    Petrol
280                       brio           5.25       14465    Petrol
281                       city           2.10       50456    Petrol
282                       city           8.25       63000    Diesel
283                       city           8.99        9010    Petrol
284                       brio           3.50        9800    Petrol
285                       jazz           7.40       15059    Petrol
286                       jazz           5.65       28569    Petrol
287                      amaze           5.75       44000    Petrol
288                       city           8.40       34000    Petrol
289                       city          10.11       10980    Petrol
290                      amaze           4.50       19000    Petrol
291                       brio           5.40       31427    Petrol
292                       jazz           6.40       12000    Petrol

In [106]:
print(y)

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     1
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     1
41     0
42     0
43     0
44     0
45     1
46     0
47     0
48     0
49     1
50     1
51     1
52     1
53     1
54     0
55     1
56     0
57     0
58     0
59     1
60     0
61     0
62     1
63     1
64     1
65     0
66     1
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     1
78     1
79     1
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     1
94     1
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    1
156    0
157    0
158    0
159    1
160    0
161    0
162    0
163    0
164    0
165    1
166    0
167    0
168    0
169    0
170    0
171    0
172    0
173    1
174    0
175    0
176    0
177    1
178    1
179    0
180    0
181    0
182    0
183    0
184    0
185    1
186    1
187    0
188    0
189    0
190    0
191    0
192    0
193    0
194    0
195    0
196    1
197    0
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    1
208    0
209    0
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    0
218    0
219    0
220    0
221    1
222    0
223    0
224    1
225    0
226    0
227    0
228    0
229    0
230    0
231    0
232    1
233    0
234    0
235    0
236    0
237    0
238    0
239    0
240    0
241    0
242    0
243    0
244    0
245    0
246    0
247    0
248    0
249    0
250    0
251    0
252    1
253    0
254    0
255    0
256    0
257    0
258    0
259    0
260    0
261    0
262    0
263    0
264    0
265    0
266    0
267    0
268    0
269    0
270    0
271    0
272    0
273    0
274    0
275    1
276    0
277    0
278    0
279    0
280    0
281    0
282    0
283    0
284    0
285    1
286    0
287    1
288    0
289    0
290    0
291    0
292    0
293    0
294    0
295    0
296    0
297    0
298    0
299    0
300    0
Name: Transmission, dtype: int64

In [107]:
oe = OneHotEncoder(drop = 'first' , sparse_output = False , dtype = int)
#oe.fit(x_train , y_train)
x_train_new = oe.fit_transform(x_train[['Fuel_Type' , 'Seller_Type']])
x_test_new = oe.transform(x_test[['Fuel_Type' , 'Seller_Type']])

In [108]:
print('x_train_shape :- ' , x_train.shape)
print('x_train_new_shape :- ' , x_train_new.shape)

x_train_shape :-  (225, 5)
x_train_new_shape :-  (225, 3)

In [109]:
print(x_train)

                      Car_Name  Selling_Price  Kms_Driven Fuel_Type  \
260                       city           9.15       29223    Petrol
111  Royal Enfield Thunder 350           1.15        8700    Petrol
29                        ciaz           7.45       45000    Diesel
171           Hero Passion Pro           0.40        6700    Petrol
278                       jazz           6.00        4000    Petrol
180     Hero Honda Passion Pro           0.30       60000    Petrol
300                       brio           5.30        5464    Petrol
272                       city           7.50       27600    Petrol
254                       city           5.25       54242    Petrol
104  Royal Enfield Classic 350           1.35        4100    Petrol
220                        eon           3.50       38488    Petrol
135           Bajaj Pulsar 150           0.65        5000    Petrol
266                      amaze           3.65       35000    Petrol
21                       ignis           4.90        2400    Petrol
76               corolla altis           5.50       72000    Petrol
249                        i20           5.25       17000    Petrol
215                      verna           4.50       36100    Petrol
153        Bajaj Pulsar NS 200           0.50       45000    Petrol
241                      xcent           4.75       35866    Petrol
103          Bajaj Dominar 400           1.45        1200    Petrol
33                      ertiga           6.00       45000    Diesel
20                    alto k10           2.85       25000    Petrol
149         Bajaj Pulsar 220 F           0.51       24000    Petrol
3                      wagon r           2.85        5200    Petrol
288                       city           8.40       34000    Petrol
281                       city           2.10       50456    Petrol
183         Bajaj Discover 100           0.27       21000    Petrol
173                  Activa 4g           0.40        1300    Petrol
222                        i20           6.00       77632    Diesel
11                        ciaz           6.85       51000    Diesel
56                 etios cross           4.50       40534    Petrol
223                      verna           8.25       61381    Diesel
136              Honda CBR 150           0.65       23500    Petrol
224                      verna           5.11       36198    Petrol
130       Honda CB Hornet 160R           0.75       11000    Petrol
13                      ertiga           6.10       26000    Petrol
48                      ertiga           5.80       25870    Petrol
54                      innova           2.75       90000    Petrol
216                        eon           2.90       12500    Petrol
8                         ciaz           8.75       20273    Diesel
2                         ciaz           7.25        6900    Petrol
99                    fortuner           9.65       50024    Diesel
63                    fortuner          23.50       47000    Diesel
197           Honda CB twister           0.16       33000    Petrol
37                         800           0.35      127000    Petrol
231                      verna           9.25       15001    Petrol
264                      amaze           4.00       40026    Petrol
162        Bajaj Pulsar NS 200           0.45       14500    Petrol
6                         ciaz           6.75       18796    Petrol
199             Honda CB Shine           0.12       53000    Petrol
189        Hero Super Splendor           0.20       55000    Petrol
122   Royal Enfield Bullet 350           1.05        6000    Petrol
187           Honda CB twister           0.25       32000    Petrol
246                        i20           3.75       35000    Petrol
176              Honda Karizma           0.35       30000    Petrol
127          Bajaj Avenger 150           0.75        7000    Petrol
283                       city           8.99        9010    Petrol
87               corolla altis           5.90       56000    Petrol
60               corolla altis           6.95       40001    Petrol
211                    elantra          11.75       43535    Diesel
10                    alto 800           2.85        2135    Petrol
261                       brio           5.50        5600    Petrol
228                      verna           4.95       60000    Diesel
166           Hero Passion Pro           0.45        1000    Petrol
218                      verna           6.45       45078    Petrol
257                       city           8.50       40324    Petrol
234                  grand i10           5.50        4492    Petrol
14                       dzire           2.25       77427    Petrol
157          Yamaha FZ S V 2.0           0.48       23000    Petrol
174           Honda CB Unicorn           0.38       38600    Petrol
225                        i10           2.70       22517    Petrol
116  Royal Enfield Classic 350           1.10       33000    Petrol
195              Bajaj  ct 100           0.18       35000    Petrol
43                       dzire           5.50       45780    Diesel
98               corolla altis           7.05       45000    Petrol
46                        ritz           2.65       64532    Petrol
47                     wagon r           1.05       65000    Petrol
177           Honda Activa 125           0.35       24000    Petrol
110                  KTM RC200           1.20        6000    Petrol
105                  KTM RC390           1.35       21700    Petrol
38                    alto k10           3.00       10079    Petrol
101         UM Renegade Mojave           1.70        1400    Petrol
235                      verna           9.10       15141    Petrol
138       Honda CB Hornet 160R           0.60       15000    Petrol
270                       city           4.10       69341    Petrol
89                     etios g           4.75       40000    Petrol
19                         sx4           2.65       41442    Petrol
221                        i20           4.50       32000    Petrol
286                       jazz           5.65       28569    Petrol
268                       brio           4.80       19000    Petrol
168           Honda CB Trigger           0.42       12000    Petrol
106             Hyosung GT250R           1.35       16500    Petrol
65                  etios liva           4.75       45000    Diesel
296                       city           9.50       33988    Diesel
45                        ciaz           7.50       15000    Petrol
102                  KTM RC200           1.65        4000    Petrol
41                    alto k10           2.55       46706    Petrol
255                       brio           3.00       53675    Petrol
70                  etios liva           3.95       71000    Diesel
112              KTM 390 Duke            1.15        7000    Petrol
77                     corolla           1.50      135154    Petrol
24                     wagon r           2.90       56879    Petrol
26                       swift           4.15       55138    Petrol
5                vitara brezza           9.25        2071    Diesel
35                         sx4           2.95       49998       CNG
75                     etios g           3.95       36000    Petrol
91                      innova          11.25       58242    Diesel
265                       jazz           6.50       21200    Petrol
244                      verna           5.95       49000    Diesel
23                    alto k10           2.50       45280    Petrol
212                      creta          11.25       22671    Petrol
154              Yamaha Fazer            0.50        8000    Petrol
275                       city          10.90       30753    Petrol
125  Royal Enfield Classic 500           0.90       40000    Petrol
274                       brio           5.30       16500    Petrol
123  Royal Enfield Classic 350           1.00       46500    Petrol
148         Bajaj Pulsar 220 F           0.52       45000    Petrol
277                       city           9.70       21780    Petrol
282                       city           8.25       63000    Diesel
96                      innova          20.75       29000    Diesel
292                       jazz           6.40       12000    Petrol
247                      verna           5.95       36000    Petrol
273                       jazz           2.25       61203    Petrol
128       Honda CB Hornet 160R           0.80        3000    Petrol
267                       city           8.35       19434    Diesel
92                      innova           3.51       75000    Petrol
120         Bajaj Pulsar RS200           1.05        5700    Petrol
178                TVS Jupyter           0.35       19000    Petrol
158          Honda Dream Yuga            0.48        8600    Petrol
100  Royal Enfield Thunder 500           1.75        3000    Petrol
233                  grand i10           3.90       53000    Diesel
276                       city           8.65       24800    Petrol
186                   TVS Wego           0.25       22000    Petrol
146               Hero Extreme           0.55       15000    Petrol
200           Bajaj Pulsar 150           0.10       92233    Petrol
0                         ritz           3.35       27000    Petrol
299                       city          11.50        9000    Diesel
259                      amaze           3.90       36054    Petrol
73                  etios liva           2.65       43000    Petrol
184           Bajaj Pulsar 150           0.25       26000    Petrol
262                      amaze           4.00       40023    Petrol
152        Bajaj Pulsar NS 200           0.50       13000    Petrol
150         TVS Apache RTR 180           0.50        6000    Petrol
51                    fortuner          23.00       40000    Diesel
126          Bajaj Avenger 220           0.90        1300    Petrol
49                        ciaz           7.75       37000    Petrol
143           Yamaha FZ  v 2.0           0.60       25000    Petrol
217                        eon           3.15       15000    Petrol
97               corolla altis          17.00        8700    Petrol
192                  Hero Hunk           0.20       49000    Petrol
117  Royal Enfield Thunder 500           1.10       14000    Petrol
61                 etios cross           4.50       40588    Petrol
140              Honda CBR 150           0.60       32000    Petrol
88                  etios liva           3.45       47000    Petrol
201                        i20           3.25       58000    Diesel
108  Royal Enfield Thunder 350           1.20       18000    Petrol
39                         sx4           2.25       62000    Petrol
78               corolla altis           5.25       80000    Petrol
232                    elantra          11.45       12900    Petrol
188               Hero Glamour           0.25       18000    Petrol
113        Mahindra Mojo XT300           1.15       35000    Petrol
294                      amaze           3.75       33019    Petrol
210                        i10           3.10       35775    Petrol
144       Bajaj Pulsar  NS 200           0.60       25000    Petrol
160   Bajaj Avenger Street 220           0.45       24000    Petrol
298                       city           3.35       87934    Petrol
193         Hero  Ignitor Disc           0.20       24000    Petrol
17                      ertiga           7.75       43000    Diesel
185          Suzuki Access 125           0.25        1900    Petrol
69               corolla altis          14.25       12000    Petrol
82                      innova          23.00       15000    Diesel
287                      amaze           5.75       44000    Petrol
284                       brio           3.50        9800    Petrol
58                     etios g           4.10       39485    Petrol
28                    alto k10           1.95       44542    Petrol
236                        eon           3.10       11849    Petrol
57               corolla altis           4.75       50000    Petrol
271                       city           3.00       69562    Petrol
66                      innova          19.75       11000    Petrol
42                         sx4           1.95       58000    Petrol
18                     wagon r           3.25       35500       CNG
293                       city           3.25       38000    Petrol
226                  grand i10           5.25       24678    Petrol
172        Bajaj Pulsar 135 LS           0.40       13700    Petrol
159            Honda Activa 4G           0.45        4000    Petrol
129          Yamaha FZ S V 2.0           0.78        5000    Petrol
79                    fortuner          14.50       89000    Diesel
118  Royal Enfield Classic 350           1.10       26000    Petrol
239                        eon           2.00       23709    Petrol
81                    etios gd           4.75       40000    Diesel
132          Bajaj Avenger 220           0.75        3500    Petrol
237                      creta          11.25       68000    Diesel
115  Royal Enfield Classic 350           1.11       17500    Petrol
194           Hero  CBZ Xtreme           0.20       50000    Petrol
55               corolla altis           3.60       70000    Petrol
165                  Activa 3g           0.45         500    Petrol
27                       swift           6.00       16200    Petrol
202                  grand i10           4.40       28200    Petrol
1                          sx4           4.75       43000    Diesel
86                land cruiser          35.00       78000    Diesel
179              Honda Karizma           0.31      213000    Petrol
156                 TVS Sport            0.48       15000    Petrol
85                       camry           2.50      142000    Petrol
22                         sx4           4.40       50000    Petrol
229                        i20           3.10       52132    Diesel
114  Royal Enfield Classic 350           1.15       17000    Petrol
164       Hero Splender iSmart           0.45       14000    Petrol
133          Bajaj Avenger 220           0.72         500    Petrol
15                      ertiga           7.75       43000    Diesel
161         TVS Apache RTR 180           0.45       23000    Petrol
248                        i10           4.00       30000    Petrol
269                       city           6.70       18828    Petrol
214                  grand i10           5.25       20114    Petrol
297                       brio           4.00       60000    Petrol
253                       city           7.20       48000    Diesel
203                        i10           2.95       53460    Petrol
25                       swift           3.00       20000    Petrol
227                        i10           2.55       57000    Petrol
83                      innova          12.50       38000    Diesel
230                      verna           6.15       45000    Diesel
90               corolla altis           3.80       62000    Petrol
191         Bajaj Discover 125           0.20       25000    Petrol
36                       dzire           4.65       48767    Petrol
285                       jazz           7.40       15059    Petrol
240                      verna           5.35       32322    Diesel

    Seller_Type
260      Dealer
111  Individual
29       Dealer
171  Individual
278      Dealer
180  Individual
300      Dealer
272      Dealer
254      Dealer
104  Individual
220      Dealer
135  Individual
266      Dealer
21       Dealer
76       Dealer
249      Dealer
215      Dealer
153  Individual
241      Dealer
103  Individual
33       Dealer
20       Dealer
149  Individual
3        Dealer
288      Dealer
281      Dealer
183  Individual
173  Individual
222      Dealer
11       Dealer
56       Dealer
223      Dealer
136  Individual
224      Dealer
130  Individual
13       Dealer
48       Dealer
54   Individual
216      Dealer
8        Dealer
2        Dealer
99       Dealer
63       Dealer
197  Individual
37   Individual
231      Dealer
264      Dealer
162  Individual
6        Dealer
199  Individual
189  Individual
122  Individual
187  Individual
246      Dealer
176  Individual
127  Individual
283      Dealer
87       Dealer
60       Dealer
211      Dealer
10       Dealer
261      Dealer
228      Dealer
166  Individual
218      Dealer
257      Dealer
234      Dealer
14       Dealer
157  Individual
174  Individual
225      Dealer
116  Individual
195  Individual
43       Dealer
98       Dealer
46       Dealer
47       Dealer
177  Individual
110  Individual
105  Individual
38       Dealer
101  Individual
235      Dealer
138  Individual
270      Dealer
89       Dealer
19       Dealer
221      Dealer
286      Dealer
268      Dealer
168  Individual
106  Individual
65       Dealer
296      Dealer
45       Dealer
102  Individual
41       Dealer
255      Dealer
70       Dealer
112  Individual
77       Dealer
24       Dealer
26       Dealer
5        Dealer
35       Dealer
75       Dealer
91       Dealer
265      Dealer
244      Dealer
23       Dealer
212      Dealer
154  Individual
275      Dealer
125  Individual
274      Dealer
123  Individual
148  Individual
277      Dealer
282      Dealer
96       Dealer
292      Dealer
247      Dealer
273      Dealer
128  Individual
267      Dealer
92       Dealer
120  Individual
178  Individual
158  Individual
100  Individual
233      Dealer
276      Dealer
186  Individual
146  Individual
200  Individual
0        Dealer
299      Dealer
259      Dealer
73       Dealer
184  Individual
262      Dealer
152  Individual
150  Individual
51       Dealer
126  Individual
49       Dealer
143  Individual
217      Dealer
97       Dealer
192  Individual
117  Individual
61       Dealer
140  Individual
88       Dealer
201      Dealer
108  Individual
39       Dealer
78       Dealer
232      Dealer
188  Individual
113  Individual
294      Dealer
210      Dealer
144  Individual
160  Individual
298      Dealer
193  Individual
17       Dealer
185  Individual
69       Dealer
82       Dealer
287      Dealer
284      Dealer
58       Dealer
28       Dealer
236      Dealer
57       Dealer
271      Dealer
66       Dealer
42       Dealer
18       Dealer
293      Dealer
226      Dealer
172  Individual
159  Individual
129  Individual
79       Dealer
118  Individual
239      Dealer
81       Dealer
132  Individual
237      Dealer
115  Individual
194  Individual
55       Dealer
165  Individual
27   Individual
202      Dealer
1        Dealer
86       Dealer
179  Individual
156  Individual
85   Individual
22       Dealer
229      Dealer
114  Individual
164  Individual
133  Individual
15       Dealer
161  Individual
248      Dealer
269      Dealer
214      Dealer
297      Dealer
253      Dealer
203      Dealer
25       Dealer
227      Dealer
83       Dealer
230      Dealer
90       Dealer
191  Individual
36       Dealer
285      Dealer
240      Dealer

In [110]:
print(x_train_new)

[[0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]]

In [115]:
np.hstack((x_train[['Car_Name' , 'Selling_Price' , 'Kms_Driven']].values,x_train_new))

array([['city', 9.15, 29223, 0, 1, 0],
       ['Royal Enfield Thunder 350', 1.15, 8700, 0, 1, 1],
       ['ciaz', 7.45, 45000, 1, 0, 0],
       ...,
       ['dzire', 4.65, 48767, 0, 1, 0],
       ['jazz', 7.4, 15059, 0, 1, 0],
       ['verna', 5.35, 32322, 1, 0, 0]], shape=(225, 6), dtype=object)

In [116]:
np.hstack((x_train[['Car_Name' , 'Selling_Price' , 'Kms_Driven']].values,x_train_new)).shape

(225, 6)

one hot encoding on top categories(car name)

In [118]:
df['Car_Name'].value_counts()

Car_Name
city                         26
corolla altis                16
verna                        14
fortuner                     11
brio                         10
ciaz                          9
innova                        9
i20                           9
grand i10                     8
Royal Enfield Classic 350     7
amaze                         7
jazz                          7
sx4                           6
ertiga                        6
eon                           6
swift                         5
alto k10                      5
i10                           5
ritz                          4
wagon r                       4
dzire                         4
etios liva                    4
Royal Enfield Thunder 350     4
Bajaj Pulsar 150              4
etios cross                   3
etios g                       3
Royal Enfield Thunder 500     3
Bajaj Avenger 220             3
Honda CB Hornet 160R          3
Yamaha FZ S V 2.0             3
TVS Apache RTR 160            3
Bajaj Pulsar NS 200           3
xcent                         3
creta                         3
KTM RC200                     2
Royal Enfield Classic 500     2
Honda CBR 150                 2
Hero Extreme                  2
Bajaj Avenger 220 dtsi        2
Yamaha FZ  v 2.0              2
Bajaj Pulsar 220 F            2
TVS Apache RTR 180            2
Honda Activa 4G               2
Hero Splender iSmart          2
Activa 3g                     2
Hero Passion Pro              2
Honda Karizma                 2
Honda CB Shine                2
Honda CB twister              2
Bajaj Discover 125            2
elantra                       2
vitara brezza                 1
s cross                       1
alto 800                      1
ignis                         1
800                           1
baleno                        1
omni                          1
corolla                       1
etios gd                      1
camry                         1
land cruiser                  1
UM Renegade Mojave            1
Bajaj Dominar 400             1
KTM RC390                     1
Hyosung GT250R                1
KTM 390 Duke                  1
Mahindra Mojo XT300           1
Bajaj Pulsar RS200            1
Royal Enfield Bullet 350      1
Bajaj Avenger 150             1
Yamaha FZ 16                  1
Bajaj Avenger 150 street      1
Bajaj Pulsar  NS 200          1
Hero Passion X pro            1
Yamaha Fazer                  1
TVS Sport                     1
Honda Dream Yuga              1
Bajaj Avenger Street 220      1
Honda CB Trigger              1
Yamaha FZ S                   1
Bajaj Pulsar 135 LS           1
Activa 4g                     1
Honda CB Unicorn              1
Hero Honda CBZ extreme        1
Honda Activa 125              1
TVS Jupyter                   1
Hero Honda Passion Pro        1
Hero Splender Plus            1
Bajaj Discover 100            1
Suzuki Access 125             1
TVS Wego                      1
Hero Glamour                  1
Hero Super Splendor           1
Hero Hunk                     1
Hero  Ignitor Disc            1
Hero  CBZ Xtreme              1
Bajaj  ct 100                 1
Name: count, dtype: int64

In [119]:
counts = df['Car_Name'].value_counts()
threshold = 10

In [122]:
counts[counts < threshold].index

Index(['ciaz', 'innova', 'i20', 'grand i10', 'Royal Enfield Classic 350',
       'amaze', 'jazz', 'sx4', 'ertiga', 'eon', 'swift', 'alto k10', 'i10',
       'ritz', 'wagon r', 'dzire', 'etios liva', 'Royal Enfield Thunder 350',
       'Bajaj Pulsar 150', 'etios cross', 'etios g',
       'Royal Enfield Thunder 500', 'Bajaj Avenger 220',
       'Honda CB Hornet 160R', 'Yamaha FZ S V 2.0', 'TVS Apache RTR 160',
       'Bajaj Pulsar NS 200', 'xcent', 'creta', 'KTM RC200',
       'Royal Enfield Classic 500', 'Honda CBR 150', 'Hero Extreme',
       'Bajaj Avenger 220 dtsi', 'Yamaha FZ  v 2.0', 'Bajaj Pulsar 220 F',
       'TVS Apache RTR 180', 'Honda Activa 4G', 'Hero Splender iSmart',
       'Activa 3g', 'Hero Passion Pro', 'Honda Karizma', 'Honda CB Shine',
       'Honda CB twister', 'Bajaj Discover 125', 'elantra', 'vitara brezza',
       's cross', 'alto 800', 'ignis', '800', 'baleno', 'omni', 'corolla',
       'etios gd', 'camry', 'land cruiser', 'UM Renegade Mojave',
       'Bajaj Dominar 400', 'KTM RC390', 'Hyosung GT250R', 'KTM 390 Duke ',
       'Mahindra Mojo XT300', 'Bajaj Pulsar RS200', 'Royal Enfield Bullet 350',
       'Bajaj Avenger 150', 'Yamaha FZ 16', 'Bajaj Avenger 150 street',
       'Bajaj Pulsar  NS 200', 'Hero Passion X pro', 'Yamaha Fazer ',
       'TVS Sport ', 'Honda Dream Yuga ', 'Bajaj Avenger Street 220',
       'Honda CB Trigger', 'Yamaha FZ S ', 'Bajaj Pulsar 135 LS', 'Activa 4g',
       'Honda CB Unicorn', 'Hero Honda CBZ extreme', 'Honda Activa 125',
       'TVS Jupyter', 'Hero Honda Passion Pro', 'Hero Splender Plus',
       'Bajaj Discover 100', 'Suzuki Access 125', 'TVS Wego', 'Hero Glamour',
       'Hero Super Splendor', 'Hero Hunk', 'Hero  Ignitor Disc',
       'Hero  CBZ Xtreme', 'Bajaj  ct 100'],
      dtype='str', name='Car_Name')

In [128]:
repl = counts[counts < threshold].index
pd.get_dummies(df['Car_Name'].replace(repl , 'uncommon') , dtype = int)

     brio  city  corolla altis  fortuner  uncommon  verna
0       0     0              0         0         1      0
1       0     0              0         0         1      0
2       0     0              0         0         1      0
3       0     0              0         0         1      0
4       0     0              0         0         1      0
5       0     0              0         0         1      0
6       0     0              0         0         1      0
7       0     0              0         0         1      0
8       0     0              0         0         1      0
9       0     0              0         0         1      0
10      0     0              0         0         1      0
11      0     0              0         0         1      0
12      0     0              0         0         1      0
13      0     0              0         0         1      0
14      0     0              0         0         1      0
15      0     0              0         0         1      0
16      0     0              0         0         1      0
17      0     0              0         0         1      0
18      0     0              0         0         1      0
19      0     0              0         0         1      0
20      0     0              0         0         1      0
21      0     0              0         0         1      0
22      0     0              0         0         1      0
23      0     0              0         0         1      0
24      0     0              0         0         1      0
25      0     0              0         0         1      0
26      0     0              0         0         1      0
27      0     0              0         0         1      0
28      0     0              0         0         1      0
29      0     0              0         0         1      0
30      0     0              0         0         1      0
31      0     0              0         0         1      0
32      0     0              0         0         1      0
33      0     0              0         0         1      0
34      0     0              0         0         1      0
35      0     0              0         0         1      0
36      0     0              0         0         1      0
37      0     0              0         0         1      0
38      0     0              0         0         1      0
39      0     0              0         0         1      0
40      0     0              0         0         1      0
41      0     0              0         0         1      0
42      0     0              0         0         1      0
43      0     0              0         0         1      0
44      0     0              0         0         1      0
45      0     0              0         0         1      0
46      0     0              0         0         1      0
47      0     0              0         0         1      0
48      0     0              0         0         1      0
49      0     0              0         0         1      0
50      0     0              0         1         0      0
51      0     0              0         1         0      0
52      0     0              0         0         1      0
53      0     0              0         1         0      0
54      0     0              0         0         1      0
55      0     0              1         0         0      0
56      0     0              0         0         1      0
57      0     0              1         0         0      0
58      0     0              0         0         1      0
59      0     0              0         1         0      0
60      0     0              1         0         0      0
61      0     0              0         0         1      0
62      0     0              0         1         0      0
63      0     0              0         1         0      0
64      0     0              0         1         0      0
65      0     0              0         0         1      0
66      0     0              0         0         1      0
67      0     0              0         1         0      0
68      0     0              1         0         0      0
69      0     0              1         0         0      0
70      0     0              0         0         1      0
71      0     0              1         0         0      0
72      0     0              1         0         0      0
73      0     0              0         0         1      0
74      0     0              0         0         1      0
75      0     0              0         0         1      0
76      0     0              1         0         0      0
77      0     0              0         0         1      0
78      0     0              1         0         0      0
79      0     0              0         1         0      0
80      0     0              1         0         0      0
81      0     0              0         0         1      0
82      0     0              0         0         1      0
83      0     0              0         0         1      0
84      0     0              0         0         1      0
85      0     0              0         0         1      0
86      0     0              0         0         1      0
87      0     0              1         0         0      0
88      0     0              0         0         1      0
89      0     0              0         0         1      0
90      0     0              1         0         0      0
91      0     0              0         0         1      0
92      0     0              0         0         1      0
93      0     0              0         1         0      0
94      0     0              1         0         0      0
95      0     0              1         0         0      0
96      0     0              0         0         1      0
97      0     0              1         0         0      0
98      0     0              1         0         0      0
99      0     0              0         1         0      0
100     0     0              0         0         1      0
101     0     0              0         0         1      0
102     0     0              0         0         1      0
103     0     0              0         0         1      0
104     0     0              0         0         1      0
105     0     0              0         0         1      0
106     0     0              0         0         1      0
107     0     0              0         0         1      0
108     0     0              0         0         1      0
109     0     0              0         0         1      0
110     0     0              0         0         1      0
111     0     0              0         0         1      0
112     0     0              0         0         1      0
113     0     0              0         0         1      0
114     0     0              0         0         1      0
115     0     0              0         0         1      0
116     0     0              0         0         1      0
117     0     0              0         0         1      0
118     0     0              0         0         1      0
119     0     0              0         0         1      0
120     0     0              0         0         1      0
121     0     0              0         0         1      0
122     0     0              0         0         1      0
123     0     0              0         0         1      0
124     0     0              0         0         1      0
125     0     0              0         0         1      0
126     0     0              0         0         1      0
127     0     0              0         0         1      0
128     0     0              0         0         1      0
129     0     0              0         0         1      0
130     0     0              0         0         1      0
131     0     0              0         0         1      0
132     0     0              0         0         1      0
133     0     0              0         0         1      0
134     0     0              0         0         1      0
135     0     0              0         0         1      0
136     0     0              0         0         1      0
137     0     0              0         0         1      0
138     0     0              0         0         1      0
139     0     0              0         0         1      0
140     0     0              0         0         1      0
141     0     0              0         0         1      0
142     0     0              0         0         1      0
143     0     0              0         0         1      0
144     0     0              0         0         1      0
145     0     0              0         0         1      0
146     0     0              0         0         1      0
147     0     0              0         0         1      0
148     0     0              0         0         1      0
149     0     0              0         0         1      0
150     0     0              0         0         1      0
151     0     0              0         0         1      0
152     0     0              0         0         1      0
153     0     0              0         0         1      0
154     0     0              0         0         1      0
155     0     0              0         0         1      0
156     0     0              0         0         1      0
157     0     0              0         0         1      0
158     0     0              0         0         1      0
159     0     0              0         0         1      0
160     0     0              0         0         1      0
161     0     0              0         0         1      0
162     0     0              0         0         1      0
163     0     0              0         0         1      0
164     0     0              0         0         1      0
165     0     0              0         0         1      0
166     0     0              0         0         1      0
167     0     0              0         0         1      0
168     0     0              0         0         1      0
169     0     0              0         0         1      0
170     0     0              0         0         1      0
171     0     0              0         0         1      0
172     0     0              0         0         1      0
173     0     0              0         0         1      0
174     0     0              0         0         1      0
175     0     0              0         0         1      0
176     0     0              0         0         1      0
177     0     0              0         0         1      0
178     0     0              0         0         1      0
179     0     0              0         0         1      0
180     0     0              0         0         1      0
181     0     0              0         0         1      0
182     0     0              0         0         1      0
183     0     0              0         0         1      0
184     0     0              0         0         1      0
185     0     0              0         0         1      0
186     0     0              0         0         1      0
187     0     0              0         0         1      0
188     0     0              0         0         1      0
189     0     0              0         0         1      0
190     0     0              0         0         1      0
191     0     0              0         0         1      0
192     0     0              0         0         1      0
193     0     0              0         0         1      0
194     0     0              0         0         1      0
195     0     0              0         0         1      0
196     0     0              0         0         1      0
197     0     0              0         0         1      0
198     0     0              0         0         1      0
199     0     0              0         0         1      0
200     0     0              0         0         1      0
201     0     0              0         0         1      0
202     0     0              0         0         1      0
203     0     0              0         0         1      0
204     0     0              0         0         1      0
205     0     0              0         0         1      0
206     0     0              0         0         1      0
207     0     0              0         0         1      0
208     0     0              0         0         1      0
209     0     0              0         0         1      0
210     0     0              0         0         1      0
211     0     0              0         0         1      0
212     0     0              0         0         1      0
213     0     0              0         0         1      0
214     0     0              0         0         1      0
215     0     0              0         0         0      1
216     0     0              0         0         1      0
217     0     0              0         0         1      0
218     0     0              0         0         0      1
219     0     0              0         0         0      1
220     0     0              0         0         1      0
221     0     0              0         0         1      0
222     0     0              0         0         1      0
223     0     0              0         0         0      1
224     0     0              0         0         0      1
225     0     0              0         0         1      0
226     0     0              0         0         1      0
227     0     0              0         0         1      0
228     0     0              0         0         0      1
229     0     0              0         0         1      0
230     0     0              0         0         0      1
231     0     0              0         0         0      1
232     0     0              0         0         1      0
233     0     0              0         0         1      0
234     0     0              0         0         1      0
235     0     0              0         0         0      1
236     0     0              0         0         1      0
237     0     0              0         0         1      0
238     0     0              0         0         0      1
239     0     0              0         0         1      0
240     0     0              0         0         0      1
241     0     0              0         0         1      0
242     0     0              0         0         1      0
243     0     0              0         0         1      0
244     0     0              0         0         0      1
245     0     0              0         0         0      1
246     0     0              0         0         1      0
247     0     0              0         0         0      1
248     0     0              0         0         1      0
249     0     0              0         0         1      0
250     0     0              0         0         1      0
251     0     1              0         0         0      0
252     1     0              0         0         0      0
253     0     1              0         0         0      0
254     0     1              0         0         0      0
255     1     0              0         0         0      0
256     0     1              0         0         0      0
257     0     1              0         0         0      0
258     0     1              0         0         0      0
259     0     0              0         0         1      0
260     0     1              0         0         0      0
261     1     0              0         0         0      0
262     0     0              0         0         1      0
263     0     0              0         0         1      0
264     0     0              0         0         1      0
265     0     0              0         0         1      0
266     0     0              0         0         1      0
267     0     1              0         0         0      0
268     1     0              0         0         0      0
269     0     1              0         0         0      0
270     0     1              0         0         0      0
271     0     1              0         0         0      0
272     0     1              0         0         0      0
273     0     0              0         0         1      0
274     1     0              0         0         0      0
275     0     1              0         0         0      0
276     0     1              0         0         0      0
277     0     1              0         0         0      0
278     0     0              0         0         1      0
279     0     1              0         0         0      0
280     1     0              0         0         0      0
281     0     1              0         0         0      0
282     0     1              0         0         0      0
283     0     1              0         0         0      0
284     1     0              0         0         0      0
285     0     0              0         0         1      0
286     0     0              0         0         1      0
287     0     0              0         0         1      0
288     0     1              0         0         0      0
289     0     1              0         0         0      0
290     0     0              0         0         1      0
291     1     0              0         0         0      0
292     0     0              0         0         1      0
293     0     1              0         0         0      0
294     0     0              0         0         1      0
295     0     1              0         0         0      0
296     0     1              0         0         0      0
297     1     0              0         0         0      0
298     0     1              0         0         0      0
299     0     1              0         0         0      0
300     1     0              0         0         0      0