In [47]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("covid_toy.csv")
pd.set_option('display.max_rows' , None)
df.head()
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [9]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [10]:
print(x)

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
5    84  Female    NaN    Mild  Bangalore
6    14    Male  101.0  Strong  Bangalore
7    20  Female    NaN  Strong     Mumbai
8    19  Female  100.0  Strong  Bangalore
9    64  Female  101.0    Mild      Delhi
10   75  Female    NaN    Mild      Delhi
11   65  Female   98.0    Mild     Mumbai
12   25  Female   99.0  Strong    Kolkata
13   64    Male  102.0    Mild  Bangalore
14   51    Male  104.0    Mild  Bangalore
15   70    Male  103.0  Strong    Kolkata
16   69  Female  103.0    Mild    Kolkata
17   40  Female   98.0  Strong      Delhi
18   64  Female   98.0    Mild  Bangalore
19   42  Female    NaN  Strong  Bangalore
20   12    Male   98.0  Strong  Bangalore
21   73    Male   98.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata
23   80  Female   98.0    Mild      Delhi
24   13  Female  100.0  Strong    Kolkata
25   23    Male    NaN    Mild     Mumbai
26   19  Female  100.0    Mild    Kolkata
27   33  Female  102.0  Strong      Delhi
28   16    Male  104.0    Mild    Kolkata
29   34  Female    NaN  Strong     Mumbai
30   15    Male  101.0    Mild      Delhi
31   83    Male  103.0    Mild    Kolkata
32   34  Female  101.0  Strong      Delhi
33   26  Female   98.0    Mild    Kolkata
34   74    Male  102.0    Mild     Mumbai
35   82  Female  102.0  Strong  Bangalore
36   38  Female  101.0    Mild  Bangalore
37   55    Male  100.0    Mild    Kolkata
38   49  Female  101.0    Mild      Delhi
39   50  Female  103.0    Mild    Kolkata
40   49  Female  102.0    Mild      Delhi
41   82    Male    NaN    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
43   22  Female   99.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
46   19  Female  101.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
49   44    Male  104.0    Mild     Mumbai
50   19    Male  101.0    Mild      Delhi
51   11  Female  100.0  Strong    Kolkata
52   47  Female  100.0  Strong  Bangalore
53   83    Male   98.0    Mild      Delhi
54   60  Female   99.0    Mild     Mumbai
55   81  Female  101.0    Mild     Mumbai
56   71    Male    NaN  Strong    Kolkata
57   49  Female   99.0  Strong  Bangalore
58   23    Male   98.0  Strong     Mumbai
59    6  Female  104.0    Mild    Kolkata
60   24  Female  102.0  Strong  Bangalore
61   81  Female   98.0  Strong     Mumbai
62   56  Female  104.0  Strong  Bangalore
63   10    Male  100.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
65   69  Female  102.0    Mild  Bangalore
66   51    Male  104.0    Mild    Kolkata
67   65    Male   99.0    Mild  Bangalore
68   54  Female  104.0  Strong    Kolkata
69   73  Female  103.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
71   75  Female  104.0  Strong      Delhi
72   83  Female  101.0    Mild    Kolkata
73   34    Male   98.0  Strong    Kolkata
74   34  Female  104.0  Strong      Delhi
75    5    Male  102.0    Mild    Kolkata
76   80    Male  100.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
78   11    Male  100.0    Mild  Bangalore
79   48  Female  103.0    Mild    Kolkata
80   14  Female   99.0    Mild     Mumbai
81   65    Male   99.0    Mild      Delhi
82   24    Male   98.0    Mild    Kolkata
83   17  Female  104.0    Mild    Kolkata
84   69  Female   98.0  Strong     Mumbai
85   16  Female  103.0    Mild  Bangalore
86   25    Male  104.0    Mild  Bangalore
87   47    Male  101.0  Strong  Bangalore
88    5  Female  100.0    Mild    Kolkata
89   46    Male  103.0  Strong  Bangalore
90   59  Female   99.0  Strong      Delhi
91   38    Male    NaN    Mild      Delhi
92   82  Female  102.0  Strong    Kolkata
93   27    Male  100.0    Mild    Kolkata
94   79    Male    NaN  Strong    Kolkata
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

In [11]:
print(y)

0      No
1     Yes
2      No
3      No
4      No
5     Yes
6      No
7     Yes
8      No
9      No
10     No
11    Yes
12     No
13    Yes
14     No
15    Yes
16    Yes
17     No
18    Yes
19    Yes
20     No
21    Yes
22    Yes
23    Yes
24     No
25     No
26    Yes
27     No
28     No
29    Yes
30    Yes
31     No
32    Yes
33     No
34    Yes
35     No
36     No
37     No
38    Yes
39     No
40     No
41    Yes
42    Yes
43    Yes
44     No
45     No
46     No
47     No
48     No
49     No
50    Yes
51    Yes
52    Yes
53    Yes
54    Yes
55    Yes
56     No
57     No
58    Yes
59    Yes
60    Yes
61     No
62    Yes
63     No
64     No
65     No
66     No
67     No
68     No
69     No
70     No
71     No
72     No
73    Yes
74     No
75    Yes
76    Yes
77     No
78    Yes
79    Yes
80    Yes
81     No
82    Yes
83     No
84     No
85    Yes
86    Yes
87     No
88     No
89     No
90     No
91    Yes
92     No
93    Yes
94    Yes
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, dtype: str

In [17]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

NORMAL METHOD

Applysing Simple Imputer

In [20]:
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.transform(x_test[['fever']])
print(x_train_fever.shape)
print(x_test_fever.shape)

(80, 1)
(20, 1)

Applying Ordinal Encoding

In [21]:
x_train

    age  gender  fever   cough       city
28   16    Male  104.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
7    20  Female    NaN  Strong     Mumbai
16   69  Female  103.0    Mild    Kolkata
91   38    Male    NaN    Mild      Delhi
44   20    Male  102.0  Strong      Delhi
32   34  Female  101.0  Strong      Delhi
20   12    Male   98.0  Strong  Bangalore
42   27    Male  100.0    Mild      Delhi
64   42    Male  104.0    Mild     Mumbai
93   27    Male  100.0    Mild    Kolkata
36   38  Female  101.0    Mild  Bangalore
15   70    Male  103.0  Strong    Kolkata
5    84  Female    NaN    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
75    5    Male  102.0    Mild    Kolkata
70   68  Female  101.0  Strong      Delhi
27   33  Female  102.0  Strong      Delhi
43   22  Female   99.0    Mild  Bangalore
13   64    Male  102.0    Mild  Bangalore
3    31  Female   98.0    Mild    Kolkata
63   10    Male  100.0    Mild  Bangalore
29   34  Female    NaN  Strong     Mumbai
23   80  Female   98.0    Mild      Delhi
10   75  Female    NaN    Mild      Delhi
19   42  Female    NaN  Strong  Bangalore
39   50  Female  103.0    Mild    Kolkata
14   51    Male  104.0    Mild  Bangalore
58   23    Male   98.0  Strong     Mumbai
87   47    Male  101.0  Strong  Bangalore
50   19    Male  101.0    Mild      Delhi
84   69  Female   98.0  Strong     Mumbai
79   48  Female  103.0    Mild    Kolkata
34   74    Male  102.0    Mild     Mumbai
33   26  Female   98.0    Mild    Kolkata
74   34  Female  104.0  Strong      Delhi
89   46    Male  103.0  Strong  Bangalore
2    42    Male  101.0    Mild      Delhi
46   19  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
65   69  Female  102.0    Mild  Bangalore
68   54  Female  104.0  Strong    Kolkata
55   81  Female  101.0    Mild     Mumbai
8    19  Female  100.0  Strong  Bangalore
95   12  Female  104.0    Mild  Bangalore
71   75  Female  104.0  Strong      Delhi
60   24  Female  102.0  Strong  Bangalore
25   23    Male    NaN    Mild     Mumbai
45   72    Male   99.0    Mild  Bangalore
11   65  Female   98.0    Mild     Mumbai
35   82  Female  102.0  Strong  Bangalore
31   83    Male  103.0    Mild    Kolkata
78   11    Male  100.0    Mild  Bangalore
17   40  Female   98.0  Strong      Delhi
98    5  Female   98.0  Strong     Mumbai
53   83    Male   98.0    Mild      Delhi
24   13  Female  100.0  Strong    Kolkata
99   10  Female   98.0  Strong    Kolkata
9    64  Female  101.0    Mild      Delhi
56   71    Male    NaN  Strong    Kolkata
86   25    Male  104.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
26   19  Female  100.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
62   56  Female  104.0  Strong  Bangalore
90   59  Female   99.0  Strong      Delhi
51   11  Female  100.0  Strong    Kolkata
92   82  Female  102.0  Strong    Kolkata
30   15    Male  101.0    Mild      Delhi
96   51  Female  101.0  Strong    Kolkata
0    60    Male  103.0    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore
49   44    Male  104.0    Mild     Mumbai
81   65    Male   99.0    Mild      Delhi
22   71  Female   98.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
6    14    Male  101.0  Strong  Bangalore
41   82    Male    NaN    Mild    Kolkata
80   14  Female   99.0    Mild     Mumbai

In [24]:
oe = OrdinalEncoder(categories = [['Mild' , 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.transform(x_test[['cough']])

print(x_train_cough.shape)
print(x_test_cough.shape)
print(x_train_cough)

(80, 1)
(20, 1)
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]

One Hot Encoding

In [28]:
print(x_train)

    age  gender  fever   cough       city
28   16    Male  104.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
7    20  Female    NaN  Strong     Mumbai
16   69  Female  103.0    Mild    Kolkata
91   38    Male    NaN    Mild      Delhi
44   20    Male  102.0  Strong      Delhi
32   34  Female  101.0  Strong      Delhi
20   12    Male   98.0  Strong  Bangalore
42   27    Male  100.0    Mild      Delhi
64   42    Male  104.0    Mild     Mumbai
93   27    Male  100.0    Mild    Kolkata
36   38  Female  101.0    Mild  Bangalore
15   70    Male  103.0  Strong    Kolkata
5    84  Female    NaN    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
75    5    Male  102.0    Mild    Kolkata
70   68  Female  101.0  Strong      Delhi
27   33  Female  102.0  Strong      Delhi
43   22  Female   99.0    Mild  Bangalore
13   64    Male  102.0    Mild  Bangalore
3    31  Female   98.0    Mild    Kolkata
63   10    Male  100.0    Mild  Bangalore
29   34  Female    NaN  Strong     Mumbai
23   80  Female   98.0    Mild      Delhi
10   75  Female    NaN    Mild      Delhi
19   42  Female    NaN  Strong  Bangalore
39   50  Female  103.0    Mild    Kolkata
14   51    Male  104.0    Mild  Bangalore
58   23    Male   98.0  Strong     Mumbai
87   47    Male  101.0  Strong  Bangalore
50   19    Male  101.0    Mild      Delhi
84   69  Female   98.0  Strong     Mumbai
79   48  Female  103.0    Mild    Kolkata
34   74    Male  102.0    Mild     Mumbai
33   26  Female   98.0    Mild    Kolkata
74   34  Female  104.0  Strong      Delhi
89   46    Male  103.0  Strong  Bangalore
2    42    Male  101.0    Mild      Delhi
46   19  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
65   69  Female  102.0    Mild  Bangalore
68   54  Female  104.0  Strong    Kolkata
55   81  Female  101.0    Mild     Mumbai
8    19  Female  100.0  Strong  Bangalore
95   12  Female  104.0    Mild  Bangalore
71   75  Female  104.0  Strong      Delhi
60   24  Female  102.0  Strong  Bangalore
25   23    Male    NaN    Mild     Mumbai
45   72    Male   99.0    Mild  Bangalore
11   65  Female   98.0    Mild     Mumbai
35   82  Female  102.0  Strong  Bangalore
31   83    Male  103.0    Mild    Kolkata
78   11    Male  100.0    Mild  Bangalore
17   40  Female   98.0  Strong      Delhi
98    5  Female   98.0  Strong     Mumbai
53   83    Male   98.0    Mild      Delhi
24   13  Female  100.0  Strong    Kolkata
99   10  Female   98.0  Strong    Kolkata
9    64  Female  101.0    Mild      Delhi
56   71    Male    NaN  Strong    Kolkata
86   25    Male  104.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
26   19  Female  100.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
62   56  Female  104.0  Strong  Bangalore
90   59  Female   99.0  Strong      Delhi
51   11  Female  100.0  Strong    Kolkata
92   82  Female  102.0  Strong    Kolkata
30   15    Male  101.0    Mild      Delhi
96   51  Female  101.0  Strong    Kolkata
0    60    Male  103.0    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore
49   44    Male  104.0    Mild     Mumbai
81   65    Male   99.0    Mild      Delhi
22   71  Female   98.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
6    14    Male  101.0  Strong  Bangalore
41   82    Male    NaN    Mild    Kolkata
80   14  Female   99.0    Mild     Mumbai

In [29]:
oh = OneHotEncoder(drop = 'first' , sparse_output = False)
x_train_gender_city = oh.fit_transform(x_train[['gender' , 'city']])
x_test_gender_city = oh.transform(x_test[['gender' , 'city']])
print(x_train.shape)
print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 5)
(80, 4)
(20, 4)

In [30]:
print(x_train_gender_city)

[[1. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]]

Extracting Age colloumn

In [42]:
x_train_age = x_train[['age']].values
x_test_age = x_test[['age']].values
# x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
print(x_train_age)

[[16]
 [65]
 [20]
 [69]
 [38]
 [20]
 [34]
 [12]
 [27]
 [42]
 [27]
 [38]
 [70]
 [84]
 [79]
 [ 5]
 [68]
 [33]
 [22]
 [64]
 [31]
 [10]
 [34]
 [80]
 [75]
 [42]
 [50]
 [51]
 [23]
 [47]
 [19]
 [69]
 [48]
 [74]
 [26]
 [34]
 [46]
 [42]
 [19]
 [ 5]
 [69]
 [54]
 [81]
 [19]
 [12]
 [75]
 [24]
 [23]
 [72]
 [65]
 [82]
 [83]
 [11]
 [40]
 [ 5]
 [83]
 [13]
 [10]
 [64]
 [71]
 [25]
 [66]
 [19]
 [49]
 [56]
 [59]
 [11]
 [82]
 [15]
 [51]
 [60]
 [18]
 [44]
 [65]
 [71]
 [49]
 [73]
 [14]
 [82]
 [14]]

In [43]:
x_train_transformed = np.concatenate((x_train_age , x_train_fever , x_train_cough , x_train_gender_city) , axis = 1)
x_test_transformed = np.concatenate((x_test_age , x_test_fever , x_test_cough , x_test_gender_city) , axis = 1)

In [45]:
print(x_train_transformed)

[[ 16. 104.   0.   1.   0.   1.   0.]
 [ 65. 101.   0.   0.   0.   0.   1.]
 [ 20. 101.   1.   0.   0.   0.   1.]
 [ 69. 103.   0.   0.   0.   1.   0.]
 [ 38. 101.   0.   1.   1.   0.   0.]
 [ 20. 102.   1.   1.   1.   0.   0.]
 [ 34. 101.   1.   0.   1.   0.   0.]
 [ 12.  98.   1.   1.   0.   0.   0.]
 [ 27. 100.   0.   1.   1.   0.   0.]
 [ 42. 104.   0.   1.   0.   0.   1.]
 [ 27. 100.   0.   1.   0.   1.   0.]
 [ 38. 101.   0.   0.   0.   0.   0.]
 [ 70. 103.   1.   1.   0.   1.   0.]
 [ 84. 101.   0.   0.   0.   0.   0.]
 [ 79. 101.   1.   1.   0.   1.   0.]
 [  5. 102.   0.   1.   0.   1.   0.]
 [ 68. 101.   1.   0.   1.   0.   0.]
 [ 33. 102.   1.   0.   1.   0.   0.]
 [ 22.  99.   0.   0.   0.   0.   0.]
 [ 64. 102.   0.   1.   0.   0.   0.]
 [ 31.  98.   0.   0.   0.   1.   0.]
 [ 10. 100.   0.   1.   0.   0.   0.]
 [ 34. 101.   1.   0.   0.   0.   1.]
 [ 80.  98.   0.   0.   1.   0.   0.]
 [ 75. 101.   0.   0.   1.   0.   0.]
 [ 42. 101.   1.   0.   0.   0.   0.]
 [ 50. 103.   0.   0.   0.   1.   0.]
 [ 51. 104.   0.   1.   0.   0.   0.]
 [ 23.  98.   1.   1.   0.   0.   1.]
 [ 47. 101.   1.   1.   0.   0.   0.]
 [ 19. 101.   0.   1.   1.   0.   0.]
 [ 69.  98.   1.   0.   0.   0.   1.]
 [ 48. 103.   0.   0.   0.   1.   0.]
 [ 74. 102.   0.   1.   0.   0.   1.]
 [ 26.  98.   0.   0.   0.   1.   0.]
 [ 34. 104.   1.   0.   1.   0.   0.]
 [ 46. 103.   1.   1.   0.   0.   0.]
 [ 42. 101.   0.   1.   1.   0.   0.]
 [ 19. 101.   0.   0.   0.   0.   1.]
 [  5. 100.   0.   0.   0.   1.   0.]
 [ 69. 102.   0.   0.   0.   0.   0.]
 [ 54. 104.   1.   0.   0.   1.   0.]
 [ 81. 101.   0.   0.   0.   0.   1.]
 [ 19. 100.   1.   0.   0.   0.   0.]
 [ 12. 104.   0.   0.   0.   0.   0.]
 [ 75. 104.   1.   0.   1.   0.   0.]
 [ 24. 102.   1.   0.   0.   0.   0.]
 [ 23. 101.   0.   1.   0.   0.   1.]
 [ 72.  99.   0.   1.   0.   0.   0.]
 [ 65.  98.   0.   0.   0.   0.   1.]
 [ 82. 102.   1.   0.   0.   0.   0.]
 [ 83. 103.   0.   1.   0.   1.   0.]
 [ 11. 100.   0.   1.   0.   0.   0.]
 [ 40.  98.   1.   0.   1.   0.   0.]
 [  5.  98.   1.   0.   0.   0.   1.]
 [ 83.  98.   0.   1.   1.   0.   0.]
 [ 13. 100.   1.   0.   0.   1.   0.]
 [ 10.  98.   1.   0.   0.   1.   0.]
 [ 64. 101.   0.   0.   1.   0.   0.]
 [ 71. 101.   1.   1.   0.   1.   0.]
 [ 25. 104.   0.   1.   0.   0.   0.]
 [ 66.  99.   1.   1.   0.   0.   0.]
 [ 19. 100.   0.   0.   0.   1.   0.]
 [ 49.  99.   1.   0.   0.   0.   0.]
 [ 56. 104.   1.   0.   0.   0.   0.]
 [ 59.  99.   1.   0.   1.   0.   0.]
 [ 11. 100.   1.   0.   0.   1.   0.]
 [ 82. 102.   1.   0.   0.   1.   0.]
 [ 15. 101.   0.   1.   1.   0.   0.]
 [ 51. 101.   1.   0.   0.   1.   0.]
 [ 60. 103.   0.   1.   0.   1.   0.]
 [ 18. 104.   0.   0.   0.   0.   0.]
 [ 44. 104.   0.   1.   0.   0.   1.]
 [ 65.  99.   0.   1.   1.   0.   0.]
 [ 71.  98.   1.   0.   0.   1.   0.]
 [ 49. 102.   0.   0.   1.   0.   0.]
 [ 73. 103.   0.   0.   1.   0.   0.]
 [ 14. 101.   1.   1.   0.   0.   0.]
 [ 82. 101.   0.   1.   0.   1.   0.]
 [ 14.  99.   0.   0.   0.   0.   1.]]

In [54]:
print(x_train_transformed.shape)

(80, 7)

In [46]:
print(x_test_transformed)

[[ 16. 103.   0.   0.   0.   0.   0.]
 [ 80. 100.   0.   1.   0.   0.   0.]
 [  8. 101.   0.   0.   0.   1.   0.]
 [ 83. 101.   0.   0.   0.   1.   0.]
 [ 51. 104.   0.   1.   0.   1.   0.]
 [ 17. 104.   0.   0.   0.   1.   0.]
 [ 34.  98.   1.   1.   0.   1.   0.]
 [ 25.  99.   1.   0.   0.   1.   0.]
 [  6. 104.   0.   0.   0.   1.   0.]
 [ 20. 101.   0.   0.   0.   0.   0.]
 [ 81.  98.   1.   0.   0.   0.   1.]
 [ 55. 100.   0.   1.   0.   1.   0.]
 [ 47. 100.   1.   0.   0.   0.   0.]
 [ 24.  98.   0.   1.   0.   1.   0.]
 [ 49. 101.   0.   0.   1.   0.   0.]
 [ 27. 100.   0.   1.   1.   0.   0.]
 [ 65.  99.   0.   1.   0.   0.   0.]
 [ 73.  98.   0.   1.   0.   0.   0.]
 [ 64.  98.   0.   0.   0.   0.   0.]
 [ 60.  99.   0.   0.   0.   0.   1.]]

Using Column Transfomer

In [51]:
transformer = ColumnTransformer(transformers =[
    ('tnf1' , SimpleImputer(),['fever']),
    ('tnf2' , OrdinalEncoder(categories = [['Mild' , 'Strong']]) , ['cough']),
    ('tnf3' , OneHotEncoder(drop = 'first' , sparse_output = False) , ['gender' , 'city'])
],remainder = 'passthrough')

In [56]:
x_train_transformed_column_transformer = transformer.fit_transform(x_train)
x_test_transformed_column_transformer = transformer.transform(x_test)
print(x_train_transformed_column_transformer.shape)
print(x_test_transformed_column_transformer.shape)

(80, 7)
(20, 7)

In [57]:
print(x_train_transformed_column_transformer)

[[104.   0.   1.   0.   1.   0.  16.]
 [101.   0.   0.   0.   0.   1.  65.]
 [101.   1.   0.   0.   0.   1.  20.]
 [103.   0.   0.   0.   1.   0.  69.]
 [101.   0.   1.   1.   0.   0.  38.]
 [102.   1.   1.   1.   0.   0.  20.]
 [101.   1.   0.   1.   0.   0.  34.]
 [ 98.   1.   1.   0.   0.   0.  12.]
 [100.   0.   1.   1.   0.   0.  27.]
 [104.   0.   1.   0.   0.   1.  42.]
 [100.   0.   1.   0.   1.   0.  27.]
 [101.   0.   0.   0.   0.   0.  38.]
 [103.   1.   1.   0.   1.   0.  70.]
 [101.   0.   0.   0.   0.   0.  84.]
 [101.   1.   1.   0.   1.   0.  79.]
 [102.   0.   1.   0.   1.   0.   5.]
 [101.   1.   0.   1.   0.   0.  68.]
 [102.   1.   0.   1.   0.   0.  33.]
 [ 99.   0.   0.   0.   0.   0.  22.]
 [102.   0.   1.   0.   0.   0.  64.]
 [ 98.   0.   0.   0.   1.   0.  31.]
 [100.   0.   1.   0.   0.   0.  10.]
 [101.   1.   0.   0.   0.   1.  34.]
 [ 98.   0.   0.   1.   0.   0.  80.]
 [101.   0.   0.   1.   0.   0.  75.]
 [101.   1.   0.   0.   0.   0.  42.]
 [103.   0.   0.   0.   1.   0.  50.]
 [104.   0.   1.   0.   0.   0.  51.]
 [ 98.   1.   1.   0.   0.   1.  23.]
 [101.   1.   1.   0.   0.   0.  47.]
 [101.   0.   1.   1.   0.   0.  19.]
 [ 98.   1.   0.   0.   0.   1.  69.]
 [103.   0.   0.   0.   1.   0.  48.]
 [102.   0.   1.   0.   0.   1.  74.]
 [ 98.   0.   0.   0.   1.   0.  26.]
 [104.   1.   0.   1.   0.   0.  34.]
 [103.   1.   1.   0.   0.   0.  46.]
 [101.   0.   1.   1.   0.   0.  42.]
 [101.   0.   0.   0.   0.   1.  19.]
 [100.   0.   0.   0.   1.   0.   5.]
 [102.   0.   0.   0.   0.   0.  69.]
 [104.   1.   0.   0.   1.   0.  54.]
 [101.   0.   0.   0.   0.   1.  81.]
 [100.   1.   0.   0.   0.   0.  19.]
 [104.   0.   0.   0.   0.   0.  12.]
 [104.   1.   0.   1.   0.   0.  75.]
 [102.   1.   0.   0.   0.   0.  24.]
 [101.   0.   1.   0.   0.   1.  23.]
 [ 99.   0.   1.   0.   0.   0.  72.]
 [ 98.   0.   0.   0.   0.   1.  65.]
 [102.   1.   0.   0.   0.   0.  82.]
 [103.   0.   1.   0.   1.   0.  83.]
 [100.   0.   1.   0.   0.   0.  11.]
 [ 98.   1.   0.   1.   0.   0.  40.]
 [ 98.   1.   0.   0.   0.   1.   5.]
 [ 98.   0.   1.   1.   0.   0.  83.]
 [100.   1.   0.   0.   1.   0.  13.]
 [ 98.   1.   0.   0.   1.   0.  10.]
 [101.   0.   0.   1.   0.   0.  64.]
 [101.   1.   1.   0.   1.   0.  71.]
 [104.   0.   1.   0.   0.   0.  25.]
 [ 99.   1.   1.   0.   0.   0.  66.]
 [100.   0.   0.   0.   1.   0.  19.]
 [ 99.   1.   0.   0.   0.   0.  49.]
 [104.   1.   0.   0.   0.   0.  56.]
 [ 99.   1.   0.   1.   0.   0.  59.]
 [100.   1.   0.   0.   1.   0.  11.]
 [102.   1.   0.   0.   1.   0.  82.]
 [101.   0.   1.   1.   0.   0.  15.]
 [101.   1.   0.   0.   1.   0.  51.]
 [103.   0.   1.   0.   1.   0.  60.]
 [104.   0.   0.   0.   0.   0.  18.]
 [104.   0.   1.   0.   0.   1.  44.]
 [ 99.   0.   1.   1.   0.   0.  65.]
 [ 98.   1.   0.   0.   1.   0.  71.]
 [102.   0.   0.   1.   0.   0.  49.]
 [103.   0.   0.   1.   0.   0.  73.]
 [101.   1.   1.   0.   0.   0.  14.]
 [101.   0.   1.   0.   1.   0.  82.]
 [ 99.   0.   0.   0.   0.   1.  14.]]

In [58]:
print(x_test_transformed_column_transformer)

[[103.   0.   0.   0.   0.   0.  16.]
 [100.   0.   1.   0.   0.   0.  80.]
 [101.   0.   0.   0.   1.   0.   8.]
 [101.   0.   0.   0.   1.   0.  83.]
 [104.   0.   1.   0.   1.   0.  51.]
 [104.   0.   0.   0.   1.   0.  17.]
 [ 98.   1.   1.   0.   1.   0.  34.]
 [ 99.   1.   0.   0.   1.   0.  25.]
 [104.   0.   0.   0.   1.   0.   6.]
 [101.   0.   0.   0.   0.   0.  20.]
 [ 98.   1.   0.   0.   0.   1.  81.]
 [100.   0.   1.   0.   1.   0.  55.]
 [100.   1.   0.   0.   0.   0.  47.]
 [ 98.   0.   1.   0.   1.   0.  24.]
 [101.   0.   0.   1.   0.   0.  49.]
 [100.   0.   1.   1.   0.   0.  27.]
 [ 99.   0.   1.   0.   0.   0.  65.]
 [ 98.   0.   1.   0.   0.   0.  73.]
 [ 98.   0.   0.   0.   0.   0.  64.]
 [ 99.   0.   0.   0.   0.   1.  60.]]